window.TPP = window.TPP || {};
TPP.uid = function () {
  return (
    "b-" +
    Date.now().toString(36) +
    "-" +
    Math.random().toString(36).slice(2, 8)
  );
};
TPP.fonts = [
  ["'Courier New', monospace", "Courier New"],
  ["Georgia, serif", "Georgia"],
  ["'Times New Roman', serif", "Times New Roman"],
  ["Garamond, serif", "Garamond"],
  ["Arial, sans-serif", "Arial"],
  ["Verdana, sans-serif", "Verdana"],
];
TPP.papers = {
  white: ["White", "#ffffff", "#231f20"],
  eggshell: ["Eggshell", "#fff8e8", "#231f20"],
  aged: ["Aged", "#ead8b4", "#2c2018"],
  cream: ["Cream", "#f7ecd2", "#2a241d"],
  gray: ["Soft Gray", "#eeeeee", "#242424"],
};
TPP.textures = {
  none: "None",
  noise: "Soft Noise",
  aged: "Aged Edges",
  fiber: "Paper Fibers",
};
TPP.sizes = {
  half: { w: 0.5, h: 0.5 },
  one: { w: 1, h: 1 },
  grid16: { w: 2.125, h: 2.75 },
  eighth: { w: 2.75, h: 4.25 },
  quarter: { w: 4.25, h: 5.5 },
};
TPP.sheets = {
  letter: { w: 8.5, h: 11 },
  legal: { w: 8.5, h: 14 },
  a4: { w: 8.267, h: 11.693 },
};
TPP.fields = [
  "title",
  "author",
  "spineAuthor",
  "pubDate",
  "publisher",
  "copyright",
  "seriesName",
  "number",
  "volume",
  "printing",
  "includeToc",
  "pageSize",
  "sheetSize",
  "signatureSize",
  "customW",
  "customH",
  "margin",
  "gutterMargin",
  "fontFamily",
  "paperPreset",
  "texture",
  "pageBg",
  "pageText",
  "bodySize",
  "captionSize",
  "lineHeight",
  "paraGap",
  "justify",
  "qrDisplayMode",
  "imageUrlMode",
  "mediaCaptionSize",
  "qrLightMode",
  "qrLightColor",
  "qrDarkMode",
  "qrDarkColor",
  "coverShowTitle",
  "coverShowAuthor",
  "coverShowSeries",
  "coverShowPublisher",
  "coverOverflowImage",
  "coverClipImageToFrame",
  "coverBg1",
  "coverBg2",
  "coverText",
  "coverBorder",
  "coverBorderOn",
  "coverImgX",
  "coverImgY",
  "coverImgZoom",
  "coverImgRotate",
  "coverTitleY",
  "coverAuthorY",
  "coverSeriesY",
  "coverPublisherY",
  "coverTitleSize",
  "coverAuthorSize",
  "coverSeriesSize",
  "coverPublisherSize",
  "coverTitleColor",
  "coverAuthorColor",
  "coverSeriesColor",
  "coverPublisherColor",
  "coverStroke",
  "coverStrokeColor",
  "coverStrokeSize",
  "coverTitleStroke",
  "coverTitleStrokeColor",
  "coverTitleStrokeSize",
  "coverAuthorStroke",
  "coverAuthorStrokeColor",
  "coverAuthorStrokeSize",
  "coverSeriesStroke",
  "coverSeriesStrokeColor",
  "coverSeriesStrokeSize",
  "coverPublisherStroke",
  "coverPublisherStrokeColor",
  "coverPublisherStrokeSize",
  "backText",
  "backTextY",
  "backTextSize",
  "backTextColor",
  "backTextAlign",
  "backTextLastLine",
  "backFrameOn",
  "backClipImageToFrame",
  "backImgX",
  "backImgY",
  "backImgZoom",
  "backImgRotate",
  "spineMode",
  "paperThickness",
  "bindingAllowance",
  "spineImgX",
  "spineImgY",
  "spineImgZoom",
  "spineImgRotate",
  "spineTitleSize",
  "spineTitleX",
  "spineTitleY",
  "spineTitleWidth",
  "spineTitleAlign",
  "spineAuthorSize",
  "spineTextColor",
  "spineStroke",
  "spineStrokeColor",
  "spineStrokeSize",
  "spineTitleRotate",
  "spineAuthorOn",
  "spineAuthorRotate",
  "wrapCover",
  "wrapInside",
  "boardThickness",
  "coverPerimeterOn",
  "separateCover",
  "coverCopies",
  "coverCopiesMax",
  "pageNumMode",
  "pageOrnament",
  "pageNumLeft",
  "pageNumRight",
  "ornamentBySide",
  "reverseOrnamentsBySide",
  "chapterEndOrnament",
  "chapterEndCentered",
  "tocNumberType",
  "tocLeader",
  "tocLeaderColor",
  "showCutGuides",
  "showFoldGuides",
  "showPageGuides",
  "printTopOffset",
  "imageExportDpi",
  "sewingStations",
  "sewingGuideOpacity",
  "showSignatureOverlay",
  "signatureGuideOpacity",
  "duplexBackSides",
];
TPP.styleFields = TPP.fields.filter(function (x) {
  return ![
    "title",
    "author",
    "spineAuthor",
    "pubDate",
    "copyright",
    "seriesName",
    "number",
    "volume",
    "backText",
  ].includes(x);
});
TPP.fallbackBook = function () {
  const stamp = new Date().toISOString();
  return {
    schemaVersion: TPP.SCHEMA_VERSION || 1,
    meta: {
      id: TPP.uid(),
      revision: 1,
      subrevision: 0,
      provenance: [],
      createdAt: stamp,
      updatedAt: stamp,
      lastExportedAt: "",
      lastImportedAt: "",
      coverPreviewImageId: "",
      pageCount: 0,
    },
    title: "Santa’s Little OSHA Violation",
    author: "Lewis Moten",
    spineAuthor: "Moten, L.",
    pubDate: "2026-05-24",
    publisher: "Tiny Pockets Press",
    copyright: "© 2026 Lewis Moten. All rights reserved.",
    seriesName: "100 Word Stories Weekly Challenge",
    number: "No. 1048",
    volume: "",
    printing: "First Printing",
    includeToc: true,
    pageSize: "one",
    sheetSize: "letter",
    signatureSize: 16,
    customW: 1,
    customH: 1,
    margin: 0.08,
    gutterMargin: 0,
    fontFamily: "'Courier New', monospace",
    paperPreset: "aged",
    texture: "aged",
    pageBg: "#ead8b4",
    pageText: "#2c2018",
    bodySize: 4.5,
    captionSize: 3.8,
    mediaCaptionSize: 3,
    lineHeight: 1.5,
    paraGap: 1.5,
    justify: true,
    qrDisplayMode: "qr",
    imageUrlMode: "image",
    qrLightMode: "page",
    qrLightColor: "#ffffff",
    qrDarkMode: "contrast",
    qrDarkColor: "#000000",
    coverShowTitle: true,
    coverShowAuthor: true,
    coverShowSeries: true,
    coverShowPublisher: false,
    coverOverflowImage: true,
    coverClipImageToFrame: false,
    coverBg1: "#182b4d",
    coverBg2: "#0d0a14",
    coverText: "#f4678a",
    coverBorder: "#12af4f",
    coverBorderOn: true,
    files: [],
    textElements: [],
    imageElements: [],
    coverImageId: "",
    coverImgX: 0,
    coverImgY: 0,
    coverImgZoom: 120,
    coverImgRotate: 0,
    coverTitleY: 12,
    coverAuthorY: 72,
    coverSeriesY: 6,
    coverPublisherY: 84,
    coverTitleSize: 8,
    coverAuthorSize: 4.2,
    coverSeriesSize: 4.2,
    coverPublisherSize: 4.2,
    coverTitleColor: "#f4678a",
    coverAuthorColor: "#f4678a",
    coverSeriesColor: "#f4678a",
    coverPublisherColor: "#f4678a",
    coverStroke: true,
    coverStrokeColor: "#000000",
    coverStrokeSize: 1,
    coverTitleStroke: true,
    coverTitleStrokeColor: "#000000",
    coverTitleStrokeSize: 1,
    coverAuthorStroke: true,
    coverAuthorStrokeColor: "#000000",
    coverAuthorStrokeSize: 1,
    coverSeriesStroke: true,
    coverSeriesStrokeColor: "#000000",
    coverSeriesStrokeSize: 1,
    coverPublisherStroke: true,
    coverPublisherStrokeColor: "#000000",
    coverPublisherStrokeSize: 1,
    backText: "A tiny story printed small enough to fit in your pocket.",
    backTextY: 76,
    backTextSize: 4.5,
    backTextColor: "#fff8e8",
    backTextAlign: "center",
    backTextLastLine: "auto",
    backFrameOn: true,
    backImageId: "",
    backClipImageToFrame: false,
    backImgX: 0,
    backImgY: 0,
    backImgZoom: 120,
    backImgRotate: 0,
    spineMode: "auto",
    paperThickness: 0.004,
    bindingAllowance: 0.025,
    spineImageId: "",
    spineImgX: 0,
    spineImgY: 0,
    spineImgZoom: 100,
    spineImgRotate: 0,
    spineTitleSize: 5,
    spineTitleX: 50,
    spineTitleY: 4,
    spineTitleWidth: 100,
    spineTitleAlign: "left",
    spineAuthorSize: 4,
    spineTextColor: "#fff8e8",
    spineStroke: true,
    spineStrokeColor: "#000000",
    spineStrokeSize: 0.75,
    spineTitleRotate: true,
    spineAuthorOn: true,
    spineAuthorRotate: false,
    wrapCover: false,
    wrapInside: 0.15,
    boardThickness: 0,
    coverPerimeterOn: true,
    separateCover: true,
    coverCopies: 1,
    coverCopiesMax: true,
    pageNumMode: "center",
    pageOrnament: "",
    pageNumLeft: "",
    pageNumRight: "",
    ornamentBySide: false,
    reverseOrnamentsBySide: false,
    chapterEndOrnament: "",
    chapterEndCentered: true,
    tocNumberType: "page",
    tocLeader: "dots",
    tocLeaderColor: "#6c625a",
    showCutGuides: true,
    showFoldGuides: true,
    showPageGuides: true,
    printTopOffset: 0,
    imageExportDpi: 300,
    sewingStations: 3,
    showSignatureOverlay: true,
    sewingGuideOpacity: 0.65,
    signatureGuideOpacity: 0.65,
    duplexBackSides: false,
    coverPreview: "",
    chapters: [
      {
        id: "chapter-sample",
        title: "Santa’s Little OSHA Violation",
        text: "A jolly “Ho-ho-ho” came from behind, followed by “Hidey ho, neighbor!”\\n\\n“Hello Santa,” little Timmy replied.\\n\\n“Why the long face?” Santa asked.\\n\\nTimmy showed him a block of wood. “I’m building a pinewood derby car, but I have no tools.”\\n\\nSanta put his hands on his waist and made grunting sounds, followed by the order: “Never give up. Never surrender!”\\n\\nSanta went into his bag and grabbed a few presents, handing them over. Timmy quickly ripped open the packages, finding a chainsaw, angle grinder, nail gun, industrial CNC router, plasma cutter, and a flame thrower, while Santa shouted, “More power!”",
        imageId: "",
        imageElementId: "",
        imagePlacement: "none",
        imageZoom: 70,
        imageWidth: 70,
        imageRotate: 0,
        level: 0,
        isSubsection: false,
        isMetadata: false,
        includeInToc: true,
      },
    ],
  };
};
