window.TPP = window.TPP || {};
TPP.SCHEMA_VERSION = 4;
TPP.LIB = "tinyPocketsPressV61";
TPP.ACTIVE = "tinyPocketsPressActiveV61";
TPP.UI = "tinyPocketsPressUiV61";
TPP.library = [];
TPP.active = null;
TPP.view = "editor";
TPP.currentChapter = 0;
TPP.readerIndex = 0;
TPP.lastPages = [];
TPP.bookFingerprints = {};
TPP.bookDraftFingerprints = {};
TPP.bookRevisionTimers = {};
TPP.staleKeyLookup = [];
TPP.defaultStaleKeyLookup = [
  {
    path: "chapters[].imageWidth",
    schemaVersion: 3,
    movedTo: ["chapters[].imageZoom"],
    note: "Chapter image sizing was standardized on zoom so image elements and chapter settings use the same geometry terminology.",
  },
  {
    path: "backUseFrontImage",
    schemaVersion: 2,
    movedTo: ["backImageId"],
    note: "The back cover now chooses an explicit shared image asset instead of inheriting the front cover image through a boolean flag.",
  },
  {
    path: "coverMetaSize",
    schemaVersion: 2,
    movedTo: ["coverAuthorSize", "coverSeriesSize", "coverPublisherSize"],
    note: "Shared cover metadata sizing was replaced by per-element size controls for author, series, and publisher.",
  },
  {
    path: "coverPreview",
    schemaVersion: 3,
    movedTo: ["meta.coverPreviewImageId"],
    note: "Generated cover previews now live in the shared file registry and are referenced by id instead of embedding raw image data directly on the book.",
  },
  {
    path: "id",
    schemaVersion: 4,
    movedTo: ["meta.id"],
    note: "System-managed book identity now lives under meta so authored content is easier to hash independently from runtime metadata.",
  },
  {
    path: "revision",
    schemaVersion: 4,
    movedTo: ["meta.revision"],
    note: "Revision tracking is now grouped under meta with the rest of the non-authored bookkeeping fields.",
  },
  {
    path: "subrevision",
    schemaVersion: 4,
    movedTo: ["meta.subrevision"],
    note: "Subrevision tracking is now grouped under meta with the rest of the non-authored bookkeeping fields.",
  },
  {
    path: "provenance",
    schemaVersion: 4,
    movedTo: ["meta.provenance"],
    note: "Copy and import lineage now lives under meta so content data stays distinct from system history.",
  },
  {
    path: "createdAt",
    schemaVersion: 4,
    movedTo: ["meta.createdAt"],
    note: "Creation timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "updatedAt",
    schemaVersion: 4,
    movedTo: ["meta.updatedAt"],
    note: "Edit timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "lastExportedAt",
    schemaVersion: 4,
    movedTo: ["meta.lastExportedAt"],
    note: "Export timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "lastImportedAt",
    schemaVersion: 4,
    movedTo: ["meta.lastImportedAt"],
    note: "Import timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "coverPreviewId",
    schemaVersion: 4,
    movedTo: ["meta.coverPreviewImageId"],
    note: "The generated cover preview image reference now lives under meta and uses the clearer coverPreviewImageId name.",
  },
  {
    path: "_pageCount",
    schemaVersion: 4,
    movedTo: ["meta._pageCount"],
    note: "Derived page counts are now grouped under meta because they are generated by the app rather than authored by the user.",
  },
];

TPP.clone = function (obj) {
  return JSON.parse(JSON.stringify(obj));
};
TPP.nowIso = function () {
  return new Date().toISOString();
};
TPP.bookMeta = function (book) {
  if (!book || typeof book !== "object") return {};
  book.meta = Object.assign({}, book.meta || {});
  return book.meta;
};
TPP.bookId = function (book) {
  return TPP.bookMeta(book).id || "";
};
TPP.bookRevision = function (book) {
  return Math.max(1, Math.floor(Number(TPP.bookMeta(book).revision) || 1));
};
TPP.bookSubrevision = function (book) {
  return Math.max(0, Math.floor(Number(TPP.bookMeta(book).subrevision) || 0));
};
TPP.bookProvenance = function (book) {
  const meta = TPP.bookMeta(book);
  return Array.isArray(meta.provenance) ? meta.provenance : [];
};
TPP.bookCreatedAt = function (book) {
  return TPP.bookMeta(book).createdAt || "";
};
TPP.bookUpdatedAt = function (book) {
  return TPP.bookMeta(book).updatedAt || "";
};
TPP.bookLastExportedAt = function (book) {
  return TPP.bookMeta(book).lastExportedAt || "";
};
TPP.bookLastImportedAt = function (book) {
  return TPP.bookMeta(book).lastImportedAt || "";
};
TPP.bookCoverPreviewImageId = function (book) {
  return TPP.bookMeta(book).coverPreviewImageId || "";
};
TPP.bookPageCount = function (book) {
  const count = Number(TPP.bookMeta(book)._pageCount);
  return Number.isFinite(count) && count > 0 ? count : 0;
};
TPP.bookRevisionLabel = function (book) {
  const revision = TPP.bookRevision(book);
  const subrevision = TPP.bookSubrevision(book);
  return subrevision ? revision + "." + subrevision : String(revision);
};
TPP.compactBookMeta = function (book) {
  if (!book || !book.meta || typeof book.meta !== "object") return;
  const meta = book.meta;
  if (!meta.subrevision) delete meta.subrevision;
  if (!meta.lastExportedAt) delete meta.lastExportedAt;
  if (!meta.lastImportedAt) delete meta.lastImportedAt;
  if (!Array.isArray(meta.provenance) || !meta.provenance.length)
    delete meta.provenance;
};
TPP.bookExportName = function (book) {
  if (!book) return "book.json";
  if (TPP.active && TPP.bookId(book) === TPP.bookId(TPP.active) && TPP.sync)
    TPP.sync("nosave");
  const title = (book.title || "").trim();
  return (title || "book") + ".json";
};
TPP.hashString = function (value) {
  let hash = 2166136261;
  const text = String(value || "");
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return ("0000000" + (hash >>> 0).toString(16)).slice(-8);
};
TPP.fileAsset = function (book, id) {
  const files = Array.isArray(book && book.files) ? book.files : [];
  return (
    files.find(function (file) {
      return file && file.id === id;
    }) || null
  );
};
TPP.filePickerAssets = function (book) {
  const files = Array.isArray(book && book.files) ? book.files : [];
  return files.filter(function (file) {
    return file && !file.hiddenFromPicker;
  });
};
TPP.fileData = function (book, id) {
  const file = TPP.fileAsset(book, id);
  return file && file.data ? file.data : "";
};
TPP.fileFieldRefs = function (book) {
  const refs = {};
  const push = function (fileId, ref) {
    if (!fileId) return;
    refs[fileId] = refs[fileId] || [];
    refs[fileId].push(ref);
  };
  (Array.isArray(book && book.imageElements) ? book.imageElements : []).forEach(
    function (element) {
      if (!element || !element.fileId) return;
      let label = "Image";
      if (element.location === "front") label = "Front Cover Image";
      else if (element.location === "back") label = "Back Cover Image";
      else if (element.location === "spine") label = "Spine Image";
      else if (element.location === "chapter") {
        const chapter = ((book && book.chapters) || []).find(function (entry) {
          return entry && entry.id === element.part;
        });
        label =
          'Chapter Image: "' + ((chapter && chapter.title) || "Untitled") + '"';
      }
      push(element.fileId, {
        key:
          "imageElement:" +
          (element.id || TPP.imageElementKey(element.location, element.part)),
        label: label,
        imageElementId: element.id || "",
        location: element.location || "",
        part: element.part || "",
      });
    },
  );
  (Array.isArray(book && book.chapters) ? book.chapters : []).forEach(
    function (chapter, index) {
      if (!chapter || !chapter.imageId) return;
      if (
        (refs[chapter.imageId] || []).some(function (ref) {
          return ref.chapterId === chapter.id;
        })
      )
        return;
      push(chapter.imageId, {
        key: "chapter:" + (chapter && chapter.id ? chapter.id : index),
        label:
          'Chapter Image: "' +
          ((chapter && chapter.title) || "Chapter " + (index + 1)) +
          '"',
        chapterId: chapter && chapter.id ? chapter.id : "",
        chapterIndex: index,
      });
    },
  );
  return refs;
};
TPP.fileReferences = function (book, fileId) {
  const refs = TPP.fileFieldRefs(book);
  return refs[fileId] || [];
};
TPP.upsertFileAsset = function (book, data, type, name, options) {
  if (!book) return "";
  if (!Array.isArray(book.files)) book.files = [];
  const assetData = String(data || "").trim();
  if (!assetData) return "";
  const assetType =
    type ||
    (assetData.match(/^data:([^;,]+)/) || [])[1] ||
    "application/octet-stream";
  const hash = TPP.hashString(assetType + ":" + assetData);
  const meta = options || {};
  const existing = book.files.find(function (file) {
    return (
      file &&
      file.hash === hash &&
      file.data === assetData &&
      (file.role || "") === (meta.role || "")
    );
  });
  if (existing) return existing.id;
  const id = TPP.uid();
  book.files.push({
    id: id,
    type: assetType,
    name: name || "",
    data: assetData,
    hash: hash,
    role: meta.role || "",
    hiddenFromPicker: Boolean(meta.hiddenFromPicker),
  });
  return id;
};
TPP.setCoverPreviewAsset = function (book, data) {
  if (!book) return "";
  const meta = TPP.bookMeta(book);
  const assetData = String(data || "").trim();
  if (!assetData) {
    book.coverPreview = "";
    meta.coverPreviewImageId = "";
    return "";
  }
  const existing = meta.coverPreviewImageId
    ? TPP.fileAsset(book, meta.coverPreviewImageId)
    : null;
  const type = (assetData.match(/^data:([^;,]+)/) || [])[1] || "image/jpeg";
  const hash = TPP.hashString(type + ":" + assetData);
  if (existing) {
    existing.type = type;
    existing.name = "Generated Cover Preview";
    existing.data = assetData;
    existing.hash = hash;
    existing.role = "coverPreview";
    existing.hiddenFromPicker = true;
    book.coverPreview = assetData;
    return existing.id;
  }
  const id = TPP.upsertFileAsset(
    book,
    assetData,
    type,
    "Generated Cover Preview",
    {
      role: "coverPreview",
      hiddenFromPicker: true,
    },
  );
  meta.coverPreviewImageId = id;
  book.coverPreview = assetData;
  return id;
};
TPP.syncCoverPreviewAsset = function (book) {
  if (!book) return;
  const meta = TPP.bookMeta(book);
  if (book.coverPreview && !meta.coverPreviewImageId) {
    TPP.setCoverPreviewAsset(book, book.coverPreview);
    return;
  }
  const file = meta.coverPreviewImageId
    ? TPP.fileAsset(book, meta.coverPreviewImageId)
    : null;
  if (file) {
    file.role = "coverPreview";
    file.hiddenFromPicker = true;
    if (!file.name) file.name = "Generated Cover Preview";
    book.coverPreview = file.data || "";
  } else {
    book.coverPreview = "";
    meta.coverPreviewImageId = "";
  }
};
TPP.removeFileAsset = function (book, fileId) {
  if (!book || !Array.isArray(book.files) || !fileId) return false;
  if (TPP.fileReferences(book, fileId).length) return false;
  const before = book.files.length;
  book.files = book.files.filter(function (file) {
    return !file || file.id !== fileId;
  });
  return book.files.length !== before;
};
TPP.migrateInlineImage = function (book, sourceKey, targetKey) {
  if (!book) return;
  const data = String(book[sourceKey] || "").trim();
  if (data && !book[targetKey])
    book[targetKey] = TPP.upsertFileAsset(book, data);
  delete book[sourceKey];
};
TPP.migrateChapterInlineImage = function (book, chapter) {
  if (!book || !chapter) return;
  const data = String(chapter.imageData || "").trim();
  if (data && !chapter.imageId)
    chapter.imageId = TPP.upsertFileAsset(book, data);
  delete chapter.imageData;
};
TPP.normalizeFiles = function (book) {
  if (!book) return;
  book.files = Array.isArray(book.files) ? book.files : [];
  const seen = new Map();
  const idMap = {};
  book.files = book.files.reduce(function (list, file) {
    if (!file || !file.data) return list;
    const normalized = {
      id: file.id || TPP.uid(),
      type:
        file.type ||
        (String(file.data).match(/^data:([^;,]+)/) || [])[1] ||
        "application/octet-stream",
      name: file.name || "",
      data: file.data,
      hash: file.hash || TPP.hashString((file.type || "") + ":" + file.data),
      role: file.role || "",
      hiddenFromPicker: Boolean(file.hiddenFromPicker),
    };
    const key = normalized.hash + "::" + normalized.data;
    if (seen.has(key)) {
      idMap[normalized.id] = seen.get(key);
      return list;
    }
    seen.set(key, normalized.id);
    idMap[normalized.id] = normalized.id;
    list.push(normalized);
    return list;
  }, []);
  TPP.migrateInlineImage(book, "coverImageData", "coverImageId");
  TPP.migrateInlineImage(book, "backImageData", "backImageId");
  TPP.migrateInlineImage(book, "spineImageData", "spineImageId");
  ["coverImageId", "backImageId", "spineImageId"].forEach(function (key) {
    if (book[key] && idMap[book[key]]) book[key] = idMap[book[key]];
  });
  (Array.isArray(book.imageElements) ? book.imageElements : []).forEach(
    function (element) {
      if (element && element.fileId && idMap[element.fileId])
        element.fileId = idMap[element.fileId];
    },
  );
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      if (chapter && chapter.imageId && idMap[chapter.imageId])
        chapter.imageId = idMap[chapter.imageId];
    },
  );
};
TPP.esc = function (value) {
  return String(value ?? "").replace(/[&<>"']/g, function (ch) {
    return {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;",
    }[ch];
  });
};
TPP.signatureSize = function (value) {
  const fallback = 16;
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(4, Math.min(64, Math.round(n / 4) * 4)) || fallback;
};
TPP.sewingStations = function (value) {
  const n = Math.round(Number(value) || 0);
  return Math.max(2, Math.min(5, n || 3));
};
TPP.opacity = function (value, fallback) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(0, Math.min(1, n));
};
TPP.dpi = function (value) {
  const n = Math.round(Number(value) || 0);
  return Math.max(72, Math.min(1200, n || 300));
};
TPP.mediaCaptionSize = function (value, fallback) {
  const n = Number(value);
  const base = Number(fallback) || 3;
  if (!Number.isFinite(n)) return base;
  return Math.max(2, Math.min(12, n));
};
TPP.bookFingerprint = function (book) {
  const copy = TPP.clone(book || {});
  delete copy.schemaVersion;
  delete copy.coverPreview;
  delete copy.id;
  delete copy.revision;
  delete copy.subrevision;
  delete copy.provenance;
  delete copy.createdAt;
  delete copy.updatedAt;
  delete copy.lastExportedAt;
  delete copy.lastImportedAt;
  delete copy.coverPreviewId;
  delete copy._pageCount;
  delete copy.coverPreviewImageId;
  delete copy.meta;
  copy.files = (Array.isArray(copy.files) ? copy.files : []).filter(
    function (file) {
      return file && file.role !== "coverPreview";
    },
  );
  return JSON.stringify(copy);
};
TPP.hydrateBookDates = function (book) {
  const now = TPP.nowIso();
  const fallbackMeta = (TPP.fallbackBook && TPP.fallbackBook().meta) || {};
  if (
    !Number.isFinite(Number(book.schemaVersion)) ||
    Number(book.schemaVersion) < 1
  )
    book.schemaVersion = 1;
  book.schemaVersion = Math.max(1, Math.floor(Number(book.schemaVersion) || 1));
  const meta = Object.assign({}, fallbackMeta, book.meta || {});
  if (book.id && !meta.id) meta.id = book.id;
  if ("revision" in book && !("revision" in (book.meta || {})))
    meta.revision = book.revision;
  if ("subrevision" in book && !("subrevision" in (book.meta || {})))
    meta.subrevision = book.subrevision;
  if (!Array.isArray(meta.provenance) && Array.isArray(book.provenance))
    meta.provenance = TPP.clone(book.provenance);
  if (!Array.isArray(meta.provenance) && Array.isArray(book.ancestry))
    meta.provenance = TPP.clone(book.ancestry);
  if ("createdAt" in book && !meta.createdAt) meta.createdAt = book.createdAt;
  if ("updatedAt" in book && !meta.updatedAt) meta.updatedAt = book.updatedAt;
  if ("lastExportedAt" in book && !("lastExportedAt" in (book.meta || {})))
    meta.lastExportedAt = book.lastExportedAt;
  if ("lastImportedAt" in book && !("lastImportedAt" in (book.meta || {})))
    meta.lastImportedAt = book.lastImportedAt;
  if ("coverPreviewId" in book && !meta.coverPreviewImageId)
    meta.coverPreviewImageId = book.coverPreviewId;
  if ("coverPreviewImageId" in book && !meta.coverPreviewImageId)
    meta.coverPreviewImageId = book.coverPreviewImageId;
  if ("_pageCount" in book && !("_pageCount" in (book.meta || {})))
    meta._pageCount = book._pageCount;
  if (!meta.id) meta.id = TPP.uid();
  if (!Number.isFinite(Number(meta.revision)) || Number(meta.revision) < 1)
    meta.revision = 1;
  meta.revision = Math.max(1, Math.floor(Number(meta.revision) || 1));
  if (
    !Number.isFinite(Number(meta.subrevision)) ||
    Number(meta.subrevision) < 0
  )
    meta.subrevision = 0;
  meta.subrevision = Math.max(0, Math.floor(Number(meta.subrevision) || 0));
  if (!Array.isArray(meta.provenance)) meta.provenance = [];
  delete book.ancestry;
  if (!meta.createdAt && meta.updatedAt) meta.createdAt = meta.updatedAt;
  if (!meta.createdAt) meta.createdAt = now;
  if (!meta.updatedAt) meta.updatedAt = meta.createdAt;
  if (!("lastExportedAt" in meta)) meta.lastExportedAt = "";
  if (!("lastImportedAt" in meta)) meta.lastImportedAt = "";
  if (!("coverPreviewImageId" in meta)) meta.coverPreviewImageId = "";
  meta._pageCount = Math.max(0, Math.floor(Number(meta._pageCount) || 0));
  book.meta = meta;
  [
    "id",
    "revision",
    "subrevision",
    "provenance",
    "createdAt",
    "updatedAt",
    "lastExportedAt",
    "lastImportedAt",
    "coverPreviewId",
    "coverPreviewImageId",
    "_pageCount",
  ].forEach(function (key) {
    delete book[key];
  });
  TPP.compactBookMeta(book);
  book.schemaVersion = TPP.SCHEMA_VERSION;
  return book;
};
TPP.unwrapImportPayload = function (data) {
  if (!data || typeof data !== "object") return { kind: "book", value: data };
  if (Array.isArray(data.books))
    return {
      kind: "library",
      value: data.books,
      schemaVersion: Number(data.schemaVersion) || 1,
    };
  if (data.book && typeof data.book === "object")
    return {
      kind: "book",
      value: data.book,
      schemaVersion:
        Number(data.schemaVersion) || Number(data.book.schemaVersion) || 1,
    };
  if (data.style && typeof data.style === "object")
    return {
      kind: "style",
      value: data.style,
      schemaVersion: Number(data.schemaVersion) || 1,
    };
  return {
    kind: "book",
    value: data,
    schemaVersion: Number(data.schemaVersion) || 1,
  };
};
TPP.bookSourceEntry = function (book, action, stamp) {
  const when = stamp || TPP.nowIso();
  return {
    action: action || "copy",
    sourceId: TPP.bookId(book),
    sourceTitle: book && book.title ? book.title : "",
    sourceRevision: TPP.bookRevision(book),
    sourceSubrevision: TPP.bookSubrevision(book),
    sourceUpdatedAt: TPP.bookUpdatedAt(book) || when,
    sourceCreatedAt: TPP.bookCreatedAt(book) || when,
    recordedAt: when,
  };
};
TPP.combineProvenance = function (a, b) {
  const seen = new Set();
  return (Array.isArray(a) ? a : [])
    .concat(Array.isArray(b) ? b : [])
    .filter(function (entry) {
      const key = JSON.stringify(entry || {});
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
};
TPP.bookDescendant = function (source, overrides, action, stamp) {
  const when = stamp || TPP.nowIso();
  const descendant = TPP.norm(
    Object.assign({}, TPP.clone(source || {}), overrides || {}),
  );
  const meta = TPP.bookMeta(descendant);
  meta.id = (overrides && overrides.id) || meta.id || TPP.uid();
  meta.revision = 1;
  meta.subrevision = 0;
  meta.createdAt = when;
  meta.updatedAt = when;
  meta.lastExportedAt = "";
  meta.lastImportedAt = action === "import" ? when : "";
  meta.provenance = Array.isArray(TPP.bookProvenance(source))
    ? TPP.clone(TPP.bookProvenance(source))
    : [];
  meta.provenance.push(TPP.bookSourceEntry(source, action, when));
  return descendant;
};
TPP.bookImported = function (source, stamp) {
  const when = stamp || TPP.nowIso();
  const imported = TPP.norm(TPP.clone(source || {}));
  const meta = TPP.bookMeta(imported);
  meta.lastImportedAt = when;
  meta.provenance = TPP.combineProvenance(TPP.bookProvenance(imported), [
    TPP.bookSourceEntry(source, "import", when),
  ]);
  return imported;
};
TPP.mergeImportedBook = function (existing, incoming, stamp) {
  const when = stamp || TPP.nowIso();
  const merged = TPP.norm(
    Object.assign({}, TPP.clone(existing || {}), TPP.clone(incoming || {})),
  );
  const meta = TPP.bookMeta(merged);
  meta.id = TPP.bookId(existing) || meta.id;
  meta.createdAt = TPP.bookCreatedAt(existing) || meta.createdAt;
  meta.updatedAt = TPP.bookUpdatedAt(incoming) || meta.updatedAt;
  meta.revision = Math.max(
    1,
    TPP.bookRevision(existing),
    TPP.bookRevision(incoming),
  );
  meta.subrevision = 0;
  meta.lastImportedAt = when;
  meta.lastExportedAt =
    TPP.bookLastExportedAt(existing) || TPP.bookLastExportedAt(incoming) || "";
  meta.provenance = TPP.combineProvenance(
    TPP.combineProvenance(
      TPP.bookProvenance(existing),
      TPP.bookProvenance(incoming),
    ),
    [TPP.bookSourceEntry(incoming, "import", when)],
  );
  return merged;
};
TPP.resolveImportConflict = function (incoming, existing) {
  return Promise.resolve("cancel");
};
TPP.markBookExported = function (book, stamp) {
  if (!book) return;
  TPP.bookMeta(book).lastExportedAt = stamp || TPP.nowIso();
};
TPP.markBookImported = function (book, stamp) {
  if (!book) return;
  TPP.bookMeta(book).lastImportedAt = stamp || TPP.nowIso();
};
TPP.imageElementKey = function (location, part) {
  return String(location || "") + ":" + String(part || "");
};
TPP.findImageElement = function (book, location, part) {
  const key = TPP.imageElementKey(location, part);
  const list = Array.isArray(book && book.imageElements)
    ? book.imageElements
    : [];
  return (
    list.find(function (entry) {
      return (
        TPP.imageElementKey(entry && entry.location, entry && entry.part) ===
        key
      );
    }) || null
  );
};
TPP.findChapterImageElement = function (book, chapter) {
  if (!book || !chapter) return null;
  const list = Array.isArray(book.imageElements) ? book.imageElements : [];
  if (chapter.imageElementId) {
    const byId = list.find(function (entry) {
      return entry && entry.id === chapter.imageElementId;
    });
    if (byId) return byId;
  }
  return TPP.findImageElement(book, "chapter", chapter.id);
};
TPP.defaultImageElements = function (book, base) {
  const source = book || {};
  const fallback = base || source || {};
  return [
    {
      id: "front-cover-image",
      location: "front",
      part: "cover",
      fileId: source.coverImageId || fallback.coverImageId || "",
      x: Number(source.coverImgX) || 0,
      y: Number(source.coverImgY) || 0,
      zoom: Number(source.coverImgZoom) || Number(fallback.coverImgZoom) || 120,
      rotate: Number(source.coverImgRotate) || 0,
      placement: "cover",
    },
    {
      id: "back-cover-image",
      location: "back",
      part: "cover",
      fileId: source.backImageId || fallback.backImageId || "",
      x: Number(source.backImgX) || 0,
      y: Number(source.backImgY) || 0,
      zoom: Number(source.backImgZoom) || Number(fallback.backImgZoom) || 120,
      rotate: Number(source.backImgRotate) || 0,
      placement: "cover",
    },
    {
      id: "spine-image",
      location: "spine",
      part: "cover",
      fileId: source.spineImageId || fallback.spineImageId || "",
      x: Number(source.spineImgX) || 0,
      y: Number(source.spineImgY) || 0,
      zoom: Number(source.spineImgZoom) || Number(fallback.spineImgZoom) || 100,
      rotate: Number(source.spineImgRotate) || 0,
      placement: "cover",
    },
  ];
};
TPP.ensureChapterImageElements = function (book) {
  if (!book) return;
  book.imageElements = Array.isArray(book.imageElements)
    ? book.imageElements
    : [];
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      if (!chapter) return;
      let element = TPP.findChapterImageElement(book, chapter);
      if (!element) {
        element = {
          id: TPP.uid(),
          location: "chapter",
          part: chapter.id,
          fileId: chapter.imageId || "",
          x: 0,
          y: 0,
          zoom: Math.min(
            100,
            Math.max(10, Number(chapter.imageZoom || chapter.imageWidth) || 70),
          ),
          rotate: Number(chapter.imageRotate) || 0,
          placement: chapter.imagePlacement || "none",
        };
        book.imageElements.push(element);
      }
      if (!element.id) element.id = TPP.uid();
      element.location = "chapter";
      element.part = chapter.id;
      chapter.imageElementId = element.id;
    },
  );
  const chapterIds = new Set(
    (Array.isArray(book.chapters) ? book.chapters : []).map(function (chapter) {
      return chapter && chapter.id;
    }),
  );
  book.imageElements = book.imageElements.filter(function (element) {
    return (
      (element && element.location !== "chapter") ||
      chapterIds.has(element && element.part)
    );
  });
};
TPP.migrateImageElements = function (book, base) {
  const defaults = TPP.defaultImageElements(book, base);
  const existing = Array.isArray(book.imageElements) ? book.imageElements : [];
  const byKey = new Map(
    existing.map(function (entry) {
      return [
        TPP.imageElementKey(entry && entry.location, entry && entry.part),
        entry,
      ];
    }),
  );
  const chapterElements = existing.filter(function (entry) {
    return entry && entry.location === "chapter";
  });
  book.imageElements = defaults
    .map(function (entry) {
      return Object.assign(
        {},
        entry,
        byKey.get(TPP.imageElementKey(entry.location, entry.part)) || {},
      );
    })
    .concat(chapterElements);
  TPP.ensureChapterImageElements(book);
};
TPP.syncLegacyImageFieldsFromElements = function (book) {
  const front = TPP.findImageElement(book, "front", "cover");
  const back = TPP.findImageElement(book, "back", "cover");
  const spine = TPP.findImageElement(book, "spine", "cover");
  if (front) {
    book.coverImageId = front.fileId || "";
    book.coverImgX = Number(front.x) || 0;
    book.coverImgY = Number(front.y) || 0;
    book.coverImgZoom = Number(front.zoom) || 120;
    book.coverImgRotate = Number(front.rotate) || 0;
  }
  if (back) {
    book.backImageId = back.fileId || "";
    book.backImgX = Number(back.x) || 0;
    book.backImgY = Number(back.y) || 0;
    book.backImgZoom = Number(back.zoom) || 120;
    book.backImgRotate = Number(back.rotate) || 0;
  }
  if (spine) {
    book.spineImageId = spine.fileId || "";
    book.spineImgX = Number(spine.x) || 0;
    book.spineImgY = Number(spine.y) || 0;
    book.spineImgZoom = Number(spine.zoom) || 100;
    book.spineImgRotate = Number(spine.rotate) || 0;
  }
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      const element = TPP.findChapterImageElement(book, chapter);
      if (!element) return;
      chapter.imageElementId = element.id || "";
      chapter.imageId = element.fileId || "";
      chapter.imagePlacement = element.placement || "none";
      chapter.imageZoom = Math.min(
        100,
        Math.max(10, Number(element.zoom) || 70),
      );
      chapter.imageWidth = chapter.imageZoom;
      chapter.imageRotate = Number(element.rotate) || 0;
    },
  );
};
TPP.syncImageElementsFromLegacyFields = function (book) {
  const front = TPP.findImageElement(book, "front", "cover");
  const back = TPP.findImageElement(book, "back", "cover");
  const spine = TPP.findImageElement(book, "spine", "cover");
  if (front)
    Object.assign(front, {
      fileId: book.coverImageId || "",
      x: Number(book.coverImgX) || 0,
      y: Number(book.coverImgY) || 0,
      zoom: Number(book.coverImgZoom) || 120,
      rotate: Number(book.coverImgRotate) || 0,
      placement: "cover",
    });
  if (back)
    Object.assign(back, {
      fileId: book.backImageId || "",
      x: Number(book.backImgX) || 0,
      y: Number(book.backImgY) || 0,
      zoom: Number(book.backImgZoom) || 120,
      rotate: Number(book.backImgRotate) || 0,
      placement: "cover",
    });
  if (spine)
    Object.assign(spine, {
      fileId: book.spineImageId || "",
      x: Number(book.spineImgX) || 0,
      y: Number(book.spineImgY) || 0,
      zoom: Number(book.spineImgZoom) || 100,
      rotate: Number(book.spineImgRotate) || 0,
      placement: "cover",
    });
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      const element = TPP.findChapterImageElement(book, chapter);
      if (!element) return;
      element.fileId = chapter.imageId || element.fileId || "";
      element.zoom = Math.min(
        100,
        Math.max(10, Number(chapter.imageZoom || chapter.imageWidth) || 70),
      );
      element.rotate = Number(chapter.imageRotate) || 0;
      element.placement = chapter.imagePlacement || "none";
      chapter.imageElementId = element.id || "";
    },
  );
};
TPP.textElementKey = function (location, part) {
  return String(location || "") + ":" + String(part || "");
};
TPP.findTextElement = function (book, location, part) {
  const key = TPP.textElementKey(location, part);
  const list = Array.isArray(book && book.textElements)
    ? book.textElements
    : [];
  return (
    list.find(function (entry) {
      return (
        TPP.textElementKey(entry && entry.location, entry && entry.part) === key
      );
    }) || null
  );
};
TPP.defaultTextElements = function (book, base) {
  const source = book || {};
  const fallback = base || source || {};
  const sharedColor = source.coverText || fallback.coverText || "#ffffff";
  const sharedStrokeColor =
    source.coverStrokeColor || fallback.coverStrokeColor || "#000000";
  const sharedStrokeSize = Number.isFinite(Number(source.coverStrokeSize))
    ? Number(source.coverStrokeSize)
    : Number(fallback.coverStrokeSize) || 0;
  return [
    {
      location: "front",
      part: "title",
      enabled: source.coverShowTitle !== false,
      size:
        Number(source.coverTitleSize) || Number(fallback.coverTitleSize) || 8,
      x: 0,
      y: Number(source.coverTitleY) || Number(fallback.coverTitleY) || 12,
      width: 100,
      align: "center",
      color: source.coverTitleColor || sharedColor,
      outlineColor: source.coverTitleStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverTitleStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      location: "front",
      part: "author",
      enabled: Boolean(source.coverShowAuthor),
      size:
        Number(source.coverAuthorSize) ||
        Number(source.coverMetaSize) ||
        Number(fallback.coverAuthorSize) ||
        4.2,
      x: 0,
      y: Number(source.coverAuthorY) || Number(fallback.coverAuthorY) || 72,
      width: 100,
      align: "center",
      color: source.coverAuthorColor || sharedColor,
      outlineColor: source.coverAuthorStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverAuthorStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      location: "front",
      part: "series",
      enabled: Boolean(source.coverShowSeries),
      size:
        Number(source.coverSeriesSize) ||
        Number(source.coverMetaSize) ||
        Number(fallback.coverSeriesSize) ||
        4.2,
      x: 0,
      y: Number(source.coverSeriesY) || Number(fallback.coverSeriesY) || 6,
      width: 100,
      align: "center",
      color: source.coverSeriesColor || sharedColor,
      outlineColor: source.coverSeriesStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverSeriesStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      location: "front",
      part: "publisher",
      enabled: Boolean(source.coverShowPublisher),
      size:
        Number(source.coverPublisherSize) ||
        Number(source.coverMetaSize) ||
        Number(fallback.coverPublisherSize) ||
        4.2,
      x: 0,
      y:
        Number(source.coverPublisherY) ||
        Number(fallback.coverPublisherY) ||
        84,
      width: 100,
      align: "center",
      color: source.coverPublisherColor || sharedColor,
      outlineColor: source.coverPublisherStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverPublisherStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      location: "back",
      part: "custom",
      enabled: true,
      size: Number(source.backTextSize) || Number(fallback.backTextSize) || 4.5,
      x: 50,
      y: Number(source.backTextY) || Number(fallback.backTextY) || 76,
      width: 100,
      align: source.backTextAlign || fallback.backTextAlign || "center",
      color: source.backTextColor || fallback.backTextColor || "#ffffff",
      outlineColor: "#000000",
      outlineSize: 0,
      rotate: false,
      customText: source.backText || fallback.backText || "",
    },
    {
      location: "spine",
      part: "title",
      enabled: true,
      size:
        Number(source.spineTitleSize) || Number(fallback.spineTitleSize) || 5,
      x: Number(source.spineTitleX) || Number(fallback.spineTitleX) || 50,
      y: Number(source.spineTitleY) || Number(fallback.spineTitleY) || 4,
      width:
        Number(source.spineTitleWidth) ||
        Number(fallback.spineTitleWidth) ||
        100,
      align: source.spineTitleAlign || fallback.spineTitleAlign || "left",
      color: source.spineTextColor || fallback.spineTextColor || "#ffffff",
      outlineColor:
        source.spineStrokeColor || fallback.spineStrokeColor || "#000000",
      outlineSize:
        Number(source.spineStrokeSize) || Number(fallback.spineStrokeSize) || 0,
      rotate: source.spineTitleRotate !== false,
      customText: "",
    },
    {
      location: "spine",
      part: "author",
      enabled: source.spineAuthorOn !== false,
      size:
        Number(source.spineAuthorSize) || Number(fallback.spineAuthorSize) || 4,
      x: 50,
      y: 94,
      width: 100,
      align: "center",
      color: source.spineTextColor || fallback.spineTextColor || "#ffffff",
      outlineColor:
        source.spineStrokeColor || fallback.spineStrokeColor || "#000000",
      outlineSize:
        Number(source.spineStrokeSize) || Number(fallback.spineStrokeSize) || 0,
      rotate: Boolean(source.spineAuthorRotate),
      customText: "",
    },
  ];
};
TPP.migrateTextElements = function (book, base) {
  const defaults = TPP.defaultTextElements(book, base);
  const existing = Array.isArray(book.textElements) ? book.textElements : [];
  const byKey = new Map(
    existing.map(function (entry) {
      return [
        TPP.textElementKey(entry && entry.location, entry && entry.part),
        entry,
      ];
    }),
  );
  book.textElements = defaults.map(function (entry) {
    return Object.assign(
      {},
      entry,
      byKey.get(TPP.textElementKey(entry.location, entry.part)) || {},
    );
  });
};
TPP.textElementContent = function (book, location, part) {
  const element = TPP.findTextElement(book, location, part);
  if (element && element.part === "custom") return element.customText || "";
  if (part === "title") return String((book && book.title) || "");
  if (part === "author")
    return location === "spine"
      ? String((book && (book.spineAuthor || book.author)) || "")
      : String((book && book.author) || "");
  if (part === "series")
    return [book && book.seriesName, book && book.number]
      .filter(Boolean)
      .join(" ");
  if (part === "publisher") return String((book && book.publisher) || "");
  if (part === "copyright") return String((book && book.copyright) || "");
  return element && element.customText ? String(element.customText) : "";
};
TPP.syncLegacyTextFieldsFromElements = function (book) {
  const coverTitle = TPP.findTextElement(book, "front", "title");
  const coverAuthor = TPP.findTextElement(book, "front", "author");
  const coverSeries = TPP.findTextElement(book, "front", "series");
  const coverPublisher = TPP.findTextElement(book, "front", "publisher");
  const backCustom = TPP.findTextElement(book, "back", "custom");
  const spineTitle = TPP.findTextElement(book, "spine", "title");
  const spineAuthor = TPP.findTextElement(book, "spine", "author");
  if (coverTitle) {
    book.coverShowTitle = coverTitle.enabled !== false;
    book.coverTitleSize = Number(coverTitle.size) || book.coverTitleSize;
    book.coverTitleY = Number(coverTitle.y) || 0;
    book.coverTitleColor = coverTitle.color || book.coverTitleColor;
    book.coverTitleStrokeColor =
      coverTitle.outlineColor || book.coverTitleStrokeColor;
    book.coverTitleStrokeSize = Math.max(
      0,
      Number(coverTitle.outlineSize) || 0,
    );
  }
  if (coverAuthor) {
    book.coverShowAuthor = coverAuthor.enabled !== false;
    book.coverAuthorSize = Number(coverAuthor.size) || book.coverAuthorSize;
    book.coverAuthorY = Number(coverAuthor.y) || 0;
    book.coverAuthorColor = coverAuthor.color || book.coverAuthorColor;
    book.coverAuthorStrokeColor =
      coverAuthor.outlineColor || book.coverAuthorStrokeColor;
    book.coverAuthorStrokeSize = Math.max(
      0,
      Number(coverAuthor.outlineSize) || 0,
    );
  }
  if (coverSeries) {
    book.coverShowSeries = coverSeries.enabled !== false;
    book.coverSeriesSize = Number(coverSeries.size) || book.coverSeriesSize;
    book.coverSeriesY = Number(coverSeries.y) || 0;
    book.coverSeriesColor = coverSeries.color || book.coverSeriesColor;
    book.coverSeriesStrokeColor =
      coverSeries.outlineColor || book.coverSeriesStrokeColor;
    book.coverSeriesStrokeSize = Math.max(
      0,
      Number(coverSeries.outlineSize) || 0,
    );
  }
  if (coverPublisher) {
    book.coverShowPublisher = coverPublisher.enabled !== false;
    book.coverPublisherSize =
      Number(coverPublisher.size) || book.coverPublisherSize;
    book.coverPublisherY = Number(coverPublisher.y) || 0;
    book.coverPublisherColor = coverPublisher.color || book.coverPublisherColor;
    book.coverPublisherStrokeColor =
      coverPublisher.outlineColor || book.coverPublisherStrokeColor;
    book.coverPublisherStrokeSize = Math.max(
      0,
      Number(coverPublisher.outlineSize) || 0,
    );
  }
  if (backCustom) {
    book.backText = String(backCustom.customText || "");
    book.backTextY = Number(backCustom.y) || 0;
    book.backTextSize = Number(backCustom.size) || book.backTextSize;
    book.backTextAlign = backCustom.align || book.backTextAlign;
    book.backTextColor = backCustom.color || book.backTextColor;
  }
  if (spineTitle) {
    book.spineTitleSize = Number(spineTitle.size) || book.spineTitleSize;
    book.spineTitleX = Number(spineTitle.x) || 50;
    book.spineTitleY = Number(spineTitle.y) || 0;
    book.spineTitleWidth = Math.max(
      10,
      Math.min(100, Number(spineTitle.width) || 100),
    );
    book.spineTitleAlign = spineTitle.align || "left";
    book.spineTextColor = spineTitle.color || book.spineTextColor;
    book.spineStrokeColor = spineTitle.outlineColor || book.spineStrokeColor;
    book.spineStrokeSize = Math.max(0, Number(spineTitle.outlineSize) || 0);
    book.spineTitleRotate = spineTitle.rotate !== false;
  }
  if (spineAuthor) {
    book.spineAuthorOn = spineAuthor.enabled !== false;
    book.spineAuthorSize = Number(spineAuthor.size) || book.spineAuthorSize;
    book.spineAuthorRotate = Boolean(spineAuthor.rotate);
  }
};
TPP.syncTextElementsFromLegacyFields = function (book) {
  const backCustom = TPP.findTextElement(book, "back", "custom");
  if (backCustom) {
    backCustom.customText = String(book.backText || "");
    backCustom.size = Number(book.backTextSize) || backCustom.size || 4.5;
    backCustom.y = Number(book.backTextY) || 0;
    backCustom.align = book.backTextAlign || backCustom.align || "center";
    backCustom.color = book.backTextColor || backCustom.color || "#ffffff";
  }
};
TPP.migrateCoverTextSettings = function (book, base) {
  const sharedColor = book.coverText || base.coverText;
  const sharedStroke =
    "coverStroke" in book ? book.coverStroke : base.coverStroke;
  const sharedStrokeColor = book.coverStrokeColor || base.coverStrokeColor;
  const sharedStrokeSize = Number.isFinite(Number(book.coverStrokeSize))
    ? Number(book.coverStrokeSize)
    : base.coverStrokeSize;
  if (!("coverShowTitle" in book)) book.coverShowTitle = true;
  if (!("coverTitleColor" in book)) book.coverTitleColor = sharedColor;
  if (!("coverAuthorColor" in book)) book.coverAuthorColor = sharedColor;
  if (!("coverSeriesColor" in book)) book.coverSeriesColor = sharedColor;
  if (!("coverPublisherColor" in book)) book.coverPublisherColor = sharedColor;
  if (!("coverAuthorSize" in book))
    book.coverAuthorSize = Number(book.coverMetaSize) || base.coverAuthorSize;
  if (!("coverSeriesSize" in book))
    book.coverSeriesSize = Number(book.coverMetaSize) || base.coverSeriesSize;
  if (!("coverPublisherSize" in book))
    book.coverPublisherSize =
      Number(book.coverMetaSize) || base.coverPublisherSize;
  if (!("coverTitleStroke" in book)) book.coverTitleStroke = sharedStroke;
  if (!("coverAuthorStroke" in book)) book.coverAuthorStroke = sharedStroke;
  if (!("coverSeriesStroke" in book)) book.coverSeriesStroke = sharedStroke;
  if (!("coverPublisherStroke" in book))
    book.coverPublisherStroke = sharedStroke;
  if (!("coverTitleStrokeColor" in book))
    book.coverTitleStrokeColor = sharedStrokeColor;
  if (!("coverAuthorStrokeColor" in book))
    book.coverAuthorStrokeColor = sharedStrokeColor;
  if (!("coverSeriesStrokeColor" in book))
    book.coverSeriesStrokeColor = sharedStrokeColor;
  if (!("coverPublisherStrokeColor" in book))
    book.coverPublisherStrokeColor = sharedStrokeColor;
  if (!("coverTitleStrokeSize" in book))
    book.coverTitleStrokeSize = sharedStrokeSize;
  if (!("coverAuthorStrokeSize" in book))
    book.coverAuthorStrokeSize = sharedStrokeSize;
  if (!("coverSeriesStrokeSize" in book))
    book.coverSeriesStrokeSize = sharedStrokeSize;
  if (!("coverPublisherStrokeSize" in book))
    book.coverPublisherStrokeSize = sharedStrokeSize;
  if (book.coverTitleStroke === false) book.coverTitleStrokeSize = 0;
  if (book.coverAuthorStroke === false) book.coverAuthorStrokeSize = 0;
  if (book.coverSeriesStroke === false) book.coverSeriesStrokeSize = 0;
  if (book.coverPublisherStroke === false) book.coverPublisherStrokeSize = 0;
  book.coverTitleStroke = true;
  book.coverAuthorStroke = true;
  book.coverSeriesStroke = true;
  book.coverPublisherStroke = true;
  if (book.spineStroke === false) book.spineStrokeSize = 0;
  book.spineStroke = true;
};
TPP.norm = function (book) {
  const base = TPP.fallbackBook();
  const out = Object.assign({}, base, book || {});
  out.signatureSize = TPP.signatureSize(out.signatureSize);
  out.sewingStations = TPP.sewingStations(out.sewingStations);
  out.sewingGuideOpacity = TPP.opacity(out.sewingGuideOpacity, 0.65);
  out.signatureGuideOpacity = TPP.opacity(out.signatureGuideOpacity, 0.65);
  out.imageExportDpi = TPP.dpi(out.imageExportDpi);
  out.mediaCaptionSize = TPP.mediaCaptionSize(
    out.mediaCaptionSize,
    base.mediaCaptionSize,
  );
  TPP.migrateCoverTextSettings(out, base);
  out.chapters =
    Array.isArray(out.chapters) && out.chapters.length
      ? out.chapters
      : base.chapters;
  out.chapters = out.chapters.map(function (chapter, index) {
    const normalized = Object.assign(
      {
        id: TPP.uid(),
        title: "Chapter " + (index + 1),
        text: "",
        imageId: "",
        imageElementId: "",
        imagePlacement: "none",
        imageZoom: 70,
        imageWidth: 70,
        imageRotate: 0,
        level: 0,
        isSubsection: false,
        isMetadata: false,
        includeInToc: true,
        tocTitle: "",
      },
      chapter,
    );
    TPP.migrateChapterInlineImage(out, normalized);
    normalized.imageZoom = Math.min(
      100,
      Math.max(10, Number(normalized.imageZoom || normalized.imageWidth) || 70),
    );
    normalized.imageWidth = normalized.imageZoom;
    return normalized;
  });
  TPP.migrateTextElements(out, base);
  TPP.migrateImageElements(out, base);
  TPP.syncLegacyTextFieldsFromElements(out);
  TPP.syncLegacyImageFieldsFromElements(out);
  TPP.hydrateBookDates(out);
  TPP.normalizeFiles(out);
  TPP.syncCoverPreviewAsset(out);
  const fileIds = new Set(
    out.files.map(function (file) {
      return file.id;
    }),
  );
  ["coverImageId", "backImageId", "spineImageId"].forEach(function (key) {
    if (out[key] && !fileIds.has(out[key])) out[key] = "";
  });
  (Array.isArray(out.imageElements) ? out.imageElements : []).forEach(
    function (element) {
      if (element && element.fileId && !fileIds.has(element.fileId))
        element.fileId = "";
    },
  );
  out.chapters.forEach(function (chapter) {
    if (chapter.imageId && !fileIds.has(chapter.imageId)) chapter.imageId = "";
  });
  TPP.syncLegacyImageFieldsFromElements(out);
  TPP.syncCoverPreviewAsset(out);
  return out;
};
TPP.load = async function () {
  try {
    TPP.library = JSON.parse(localStorage.getItem(TPP.LIB) || "[]");
  } catch {
    TPP.library = [];
  }
  if (!TPP.library.length) {
    let sample = null;
    try {
      sample = await fetch("data/sample-book.json").then(function (response) {
        return response.json();
      });
    } catch {
      sample = TPP.fallbackBook();
    }
    TPP.library = [TPP.norm(sample)];
    TPP.save();
  }
  TPP.library = TPP.library.map(TPP.norm);
  TPP.bookFingerprints = {};
  TPP.bookDraftFingerprints = {};
  TPP.library.forEach(function (book) {
    const fingerprint = TPP.bookFingerprint(book);
    const bookId = TPP.bookId(book);
    TPP.bookFingerprints[bookId] = fingerprint;
    TPP.bookDraftFingerprints[bookId] = fingerprint;
  });
  const activeId = localStorage.getItem(TPP.ACTIVE);
  TPP.active =
    TPP.library.find(function (book) {
      return TPP.bookId(book) === activeId;
    }) || TPP.library[0];
};
TPP.loadStaleKeyLookup = async function () {
  try {
    const response = await fetch("data/stale-key-lookup.json");
    if (!response.ok) throw new Error("lookup");
    const data = await response.json();
    TPP.staleKeyLookup =
      Array.isArray(data) && data.length
        ? data
        : TPP.clone(TPP.defaultStaleKeyLookup);
  } catch {
    TPP.staleKeyLookup = TPP.clone(TPP.defaultStaleKeyLookup);
  }
};
TPP.clearRevisionTimer = function (bookId) {
  if (!TPP.bookRevisionTimers[bookId]) return;
  clearTimeout(TPP.bookRevisionTimers[bookId]);
  delete TPP.bookRevisionTimers[bookId];
};
TPP.scheduleRevisionCommit = function (bookId, delay) {
  if (!bookId) return;
  TPP.clearRevisionTimer(bookId);
  TPP.bookRevisionTimers[bookId] = setTimeout(
    function () {
      const book = TPP.library.find(function (entry) {
        return TPP.bookId(entry) === bookId;
      });
      if (!book) return;
      TPP.save("commit", bookId);
    },
    Math.max(100, Number(delay) || 900),
  );
};
TPP.save = function (mode, bookId) {
  mode = mode || "commit";
  const targetIds = bookId
    ? [bookId]
    : TPP.library.map(function (book) {
        return TPP.bookId(book);
      });
  TPP.library.forEach(function (book) {
    const meta = TPP.bookMeta(book);
    const currentId = TPP.bookId(book);
    if (!targetIds.includes(currentId)) return;
    TPP.hydrateBookDates(book);
    const previous = TPP.bookFingerprints[currentId];
    const priorDraft = TPP.bookDraftFingerprints[currentId];
    const current = TPP.bookFingerprint(book);
    if (mode === "draft") {
      if (priorDraft !== current) {
        if (previous !== undefined && current !== previous) {
          meta.subrevision = TPP.bookSubrevision(book) + 1;
          meta.updatedAt = TPP.nowIso();
        } else {
          meta.subrevision = 0;
        }
      }
      TPP.bookDraftFingerprints[currentId] = current;
    } else {
      TPP.clearRevisionTimer(currentId);
      if (previous !== undefined && current !== previous) {
        meta.revision = TPP.bookRevision(book) + 1;
        meta.subrevision = 0;
        meta.updatedAt = TPP.nowIso();
      } else if (meta.subrevision) {
        meta.subrevision = 0;
      }
      TPP.bookFingerprints[currentId] = current;
      TPP.bookDraftFingerprints[currentId] = current;
    }
    TPP.compactBookMeta(book);
  });
  localStorage.setItem(TPP.LIB, JSON.stringify(TPP.library));
};
TPP.setActive = function (book) {
  TPP.active = book;
  localStorage.setItem(TPP.ACTIVE, TPP.bookId(book));
  TPP.loadForm();
  if (TPP.restoreReaderUi)
    TPP.restoreReaderUi(TPP.readSettingsUi ? TPP.readSettingsUi() : {});
  TPP.renderAll();
};
TPP.download = function (name, data) {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  TPP.downloadBlob(name, blob);
};
TPP.downloadBlob = function (name, blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = String(name).replace(/[/\\?%*:|"<>]/g, "-");
  link.click();
  URL.revokeObjectURL(url);
};
TPP.showProgress = function (pct, msg) {
  const wrap = document.getElementById("progress");
  const bar = document.getElementById("progressBar");
  const text = document.getElementById("progressText");
  if (!wrap || !bar || !text) return;
  wrap.hidden = false;
  bar.style.width = Math.max(2, Math.min(100, pct)) + "%";
  text.textContent = msg || "Rendering…";
  if (pct >= 100)
    setTimeout(function () {
      wrap.hidden = true;
    }, 800);
};
TPP.file = function (event, callback) {
  const file = event.target.files && event.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = function () {
    callback(reader.result, file);
  };
  reader.readAsDataURL(file);
};
