window.TPP = window.TPP || {};
TPP.SCHEMA_VERSION = 11;
TPP.LIB = "tinyPocketsPressV61";
TPP.ACTIVE = "tinyPocketsPressActiveV61";
TPP.UI = "tinyPocketsPressUiV61";
TPP.library = [];
TPP.active = null;
TPP.view = "editor";
TPP.currentChapter = 0;
TPP.readerIndex = 0;
TPP.lastPages = [];
TPP.bookFingerprints = {};
TPP.bookDraftFingerprints = {};
TPP.bookRevisionTimers = {};
TPP.staleKeyLookup = [];
TPP.defaultStaleKeyLookup = [
  {
    path: "chapters[].imageWidth",
    schemaVersion: 3,
    movedTo: ["chapters[].imageZoom"],
    note: "Chapter image sizing was standardized on zoom so image elements and chapter settings use the same geometry terminology.",
  },
  {
    path: "backUseFrontImage",
    schemaVersion: 2,
    movedTo: ["backImageId"],
    note: "The back cover now chooses an explicit shared image asset instead of inheriting the front cover image through a boolean flag.",
  },
  {
    path: "coverMetaSize",
    schemaVersion: 2,
    movedTo: ["coverAuthorSize", "coverSeriesSize", "coverPublisherSize"],
    note: "Shared cover metadata sizing was replaced by per-element size controls for author, series, and publisher.",
  },
  {
    path: "coverPreview",
    schemaVersion: 3,
    movedTo: ["meta.coverPreviewImageId"],
    note: "Generated cover previews now live in the shared file registry and are referenced by id instead of embedding raw image data directly on the book.",
  },
  {
    path: "id",
    schemaVersion: 4,
    movedTo: ["meta.id"],
    note: "System-managed book identity now lives under meta so authored content is easier to hash independently from runtime metadata.",
  },
  {
    path: "revision",
    schemaVersion: 4,
    movedTo: ["meta.revision"],
    note: "Revision tracking is now grouped under meta with the rest of the non-authored bookkeeping fields.",
  },
  {
    path: "subrevision",
    schemaVersion: 4,
    movedTo: ["meta.subrevision"],
    note: "Subrevision tracking is now grouped under meta with the rest of the non-authored bookkeeping fields.",
  },
  {
    path: "provenance",
    schemaVersion: 4,
    movedTo: ["meta.provenance"],
    note: "Copy and import lineage now lives under meta so content data stays distinct from system history.",
  },
  {
    path: "createdAt",
    schemaVersion: 4,
    movedTo: ["meta.createdAt"],
    note: "Creation timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "updatedAt",
    schemaVersion: 4,
    movedTo: ["meta.updatedAt"],
    note: "Edit timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "lastExportedAt",
    schemaVersion: 4,
    movedTo: ["meta.lastExportedAt"],
    note: "Export timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "lastImportedAt",
    schemaVersion: 4,
    movedTo: ["meta.lastImportedAt"],
    note: "Import timestamps are now grouped under meta with other system-managed dates.",
  },
  {
    path: "coverPreviewId",
    schemaVersion: 4,
    movedTo: ["meta.coverPreviewImageId"],
    note: "The generated cover preview image reference now lives under meta and uses the clearer coverPreviewImageId name.",
  },
  {
    path: "_pageCount",
    schemaVersion: 4,
    movedTo: ["meta.pageCount"],
    note: "Derived page counts are now grouped under meta because they are generated by the app rather than authored by the user.",
  },
  {
    path: "meta._pageCount",
    schemaVersion: 5,
    movedTo: ["meta.pageCount"],
    note: "The page count field no longer uses an underscore prefix.",
  },
  {
    path: "title",
    schemaVersion: 6,
    movedTo: ["bookInfo.title"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "author",
    schemaVersion: 6,
    movedTo: ["bookInfo.author"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "pubDate",
    schemaVersion: 6,
    movedTo: ["bookInfo.pubDate"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "publisher",
    schemaVersion: 6,
    movedTo: ["bookInfo.publisher"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "copyright",
    schemaVersion: 6,
    movedTo: ["bookInfo.copyright"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "seriesName",
    schemaVersion: 6,
    movedTo: ["bookInfo.seriesName"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "number",
    schemaVersion: 6,
    movedTo: ["bookInfo.number"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "volume",
    schemaVersion: 6,
    movedTo: ["bookInfo.volume"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "printing",
    schemaVersion: 6,
    movedTo: ["bookInfo.printing"],
    note: "Core book identity and publication fields now live under bookInfo so authored bibliographic data is grouped together.",
  },
  {
    path: "pageSize",
    schemaVersion: 8,
    movedTo: ["page.pageSize"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "sheetSize",
    schemaVersion: 8,
    movedTo: ["page.sheetSize"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "signatureSize",
    schemaVersion: 8,
    movedTo: ["page.signatureSize"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "customW",
    schemaVersion: 8,
    movedTo: ["page.customW"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "customH",
    schemaVersion: 8,
    movedTo: ["page.customH"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "margin",
    schemaVersion: 8,
    movedTo: ["page.margin"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "gutterMargin",
    schemaVersion: 8,
    movedTo: ["page.gutterMargin"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "paperPreset",
    schemaVersion: 8,
    movedTo: ["page.paperPreset"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "texture",
    schemaVersion: 8,
    movedTo: ["page.texture"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "pageBg",
    schemaVersion: 8,
    movedTo: ["page.pageBg"],
    note: "Page layout and paper appearance settings now live under page.",
  },
  {
    path: "imageExportDpi",
    schemaVersion: 11,
    movedTo: [],
    note: "Page image export DPI is no longer stored on the book. It is now chosen at ZIP export time and remembered as a global app preference.",
  },
  {
    path: "fontFamily",
    schemaVersion: 8,
    movedTo: ["text.fontFamily"],
    note: "Typography settings now live under text.",
  },
  {
    path: "pageText",
    schemaVersion: 8,
    movedTo: ["text.pageText"],
    note: "Typography settings now live under text.",
  },
  {
    path: "bodySize",
    schemaVersion: 8,
    movedTo: ["text.bodySize"],
    note: "Typography settings now live under text.",
  },
  {
    path: "captionSize",
    schemaVersion: 8,
    movedTo: ["text.captionSize"],
    note: "Typography settings now live under text.",
  },
  {
    path: "lineHeight",
    schemaVersion: 8,
    movedTo: ["text.lineHeight"],
    note: "Typography settings now live under text.",
  },
  {
    path: "paraGap",
    schemaVersion: 8,
    movedTo: ["text.paraGap"],
    note: "Typography settings now live under text.",
  },
  {
    path: "justify",
    schemaVersion: 8,
    movedTo: ["text.justify"],
    note: "Typography settings now live under text.",
  },
  {
    path: "coverOverflowImage",
    schemaVersion: 9,
    movedTo: ["coverFront.overflowImage"],
    note: "Front-cover frame and background settings now live under coverFront.",
  },
  {
    path: "coverClipImageToFrame",
    schemaVersion: 9,
    movedTo: ["coverFront.clipImageToFrame"],
    note: "Front-cover frame and background settings now live under coverFront.",
  },
  {
    path: "coverBg1",
    schemaVersion: 9,
    movedTo: ["coverFront.bg1"],
    note: "Front-cover frame and background settings now live under coverFront.",
  },
  {
    path: "coverBg2",
    schemaVersion: 9,
    movedTo: ["coverFront.bg2"],
    note: "Front-cover frame and background settings now live under coverFront.",
  },
  {
    path: "coverBorder",
    schemaVersion: 9,
    movedTo: ["coverFront.border"],
    note: "Front-cover frame and background settings now live under coverFront.",
  },
  {
    path: "coverBorderOn",
    schemaVersion: 9,
    movedTo: ["coverFront.borderOn"],
    note: "Front-cover frame and background settings now live under coverFront.",
  },
  {
    path: "includeToc",
    schemaVersion: 7,
    movedTo: ["toc.enabled"],
    note: "Table of contents settings now live under toc so they are grouped separately from the rest of the book configuration.",
  },
  {
    path: "tocNumberType",
    schemaVersion: 7,
    movedTo: ["toc.numberMode"],
    note: "Table of contents settings now live under toc so they are grouped separately from the rest of the book configuration.",
  },
  {
    path: "tocLeader",
    schemaVersion: 7,
    movedTo: ["toc.leaderStyle"],
    note: "Table of contents settings now live under toc so they are grouped separately from the rest of the book configuration.",
  },
  {
    path: "tocLeaderColor",
    schemaVersion: 7,
    movedTo: ["toc.leaderColor"],
    note: "Table of contents settings now live under toc so they are grouped separately from the rest of the book configuration.",
  },
  {
    path: "toc.indentSubchapters",
    schemaVersion: 7,
    movedTo: ["toc.indentStep"],
    note: "Subchapter indentation is now controlled entirely by toc.indentStep. A value of 0 means no indentation, so the old checkbox is no longer needed.",
  },
];
TPP.BOOK_INFO_FIELDS = [
  "title",
  "author",
  "pubDate",
  "publisher",
  "copyright",
  "seriesName",
  "number",
  "volume",
  "printing",
];
TPP.TOC_FIELDS = [
  "includeToc",
  "tocNumberType",
  "tocLeader",
  "tocLeaderColor",
  "tocIndentStep",
];
TPP.PAGE_FIELDS = [
  "pageSize",
  "sheetSize",
  "signatureSize",
  "customW",
  "customH",
  "margin",
  "gutterMargin",
  "paperPreset",
  "texture",
  "pageBg",
];
TPP.TEXT_FIELDS = [
  "fontFamily",
  "pageText",
  "bodySize",
  "captionSize",
  "lineHeight",
  "paraGap",
  "justify",
];
TPP.COVER_FRONT_FIELDS = [
  "coverImageId",
  "coverOverflowImage",
  "coverClipImageToFrame",
  "coverBg1",
  "coverBg2",
  "coverBorder",
  "coverBorderOn",
];
TPP.COVER_LEGACY_FIELDS = [
  "coverShowTitle",
  "coverShowAuthor",
  "coverShowSeries",
  "coverShowPublisher",
  "coverText",
  "coverImgX",
  "coverImgY",
  "coverImgZoom",
  "coverImgRotate",
  "coverTitleY",
  "coverAuthorY",
  "coverSeriesY",
  "coverPublisherY",
  "coverTitleSize",
  "coverAuthorSize",
  "coverSeriesSize",
  "coverPublisherSize",
  "coverTitleColor",
  "coverAuthorColor",
  "coverSeriesColor",
  "coverPublisherColor",
  "coverStroke",
  "coverStrokeColor",
  "coverStrokeSize",
  "coverTitleStroke",
  "coverTitleStrokeColor",
  "coverTitleStrokeSize",
  "coverAuthorStroke",
  "coverAuthorStrokeColor",
  "coverAuthorStrokeSize",
  "coverSeriesStroke",
  "coverSeriesStrokeColor",
  "coverSeriesStrokeSize",
  "coverPublisherStroke",
  "coverPublisherStrokeColor",
  "coverPublisherStrokeSize",
];
TPP.BACK_COVER_FIELDS = [
  "backImageId",
  "backText",
  "backTextY",
  "backTextSize",
  "backTextColor",
  "backTextAlign",
  "backTextLastLine",
  "backFrameOn",
  "backClipImageToFrame",
  "backImgX",
  "backImgY",
  "backImgZoom",
  "backImgRotate",
];
TPP.SPINE_FIELDS = [
  "spineImageId",
  "spineImgX",
  "spineImgY",
  "spineImgZoom",
  "spineImgRotate",
  "spineTitleSize",
  "spineTitleX",
  "spineTitleY",
  "spineTitleWidth",
  "spineTitleAlign",
  "spineAuthorSize",
  "spineTextColor",
  "spineStroke",
  "spineStrokeColor",
  "spineStrokeSize",
  "spineTitleRotate",
  "spineAuthorOn",
  "spineAuthorRotate",
];
TPP.BACK_COVER_SCHEMA_KEYS = new Set([
  "imageElementId",
  "textLastLine",
  "frameOn",
  "clipImageToFrame",
]);
TPP.SPINE_SCHEMA_KEYS = new Set(["imageElementId"]);

TPP.clone = function (obj) {
  return JSON.parse(JSON.stringify(obj));
};
TPP.nowIso = function () {
  return new Date().toISOString();
};
TPP.bookInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().bookInfo) || {};
  book.bookInfo = Object.assign({}, fallback, book.bookInfo || {});
  return book.bookInfo;
};
TPP.attachBookInfoAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  TPP.BOOK_INFO_FIELDS.forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: function () {
        return TPP.bookInfo(book)[field];
      },
      set: function (value) {
        TPP.bookInfo(book)[field] = value;
      },
    });
  });
  return book;
};
TPP.syncBookInfoFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const info = TPP.bookInfo(book);
  TPP.BOOK_INFO_FIELDS.forEach(function (field) {
    if (field in book) info[field] = book[field];
  });
};
TPP.compactBookInfo = function (book) {
  if (!book || !book.bookInfo || typeof book.bookInfo !== "object") return;
  TPP.BOOK_INFO_FIELDS.forEach(function (field) {
    const descriptor = Object.getOwnPropertyDescriptor(book, field);
    if (
      descriptor &&
      !descriptor.get &&
      !descriptor.set &&
      descriptor.enumerable !== false
    ) {
      delete book[field];
    }
  });
};
TPP.tocInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().toc) || {};
  book.toc = Object.assign({}, fallback, book.toc || {});
  return book.toc;
};
TPP.attachTocAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  const map = {
    includeToc: "enabled",
    tocNumberType: "numberMode",
    tocLeader: "leaderStyle",
    tocLeaderColor: "leaderColor",
    tocIndentStep: "indentStep",
  };
  Object.keys(map).forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: function () {
        return TPP.tocInfo(book)[map[field]];
      },
      set: function (value) {
        TPP.tocInfo(book)[map[field]] = value;
      },
    });
  });
  return book;
};
TPP.syncTocFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const toc = TPP.tocInfo(book);
  if ("includeToc" in book) toc.enabled = book.includeToc;
  if ("tocNumberType" in book) toc.numberMode = book.tocNumberType;
  if ("tocLeader" in book) toc.leaderStyle = book.tocLeader;
  if ("tocLeaderColor" in book) toc.leaderColor = book.tocLeaderColor;
  if ("tocIndentStep" in book) toc.indentStep = book.tocIndentStep;
};
TPP.compactTocInfo = function (book) {
  if (!book || !book.toc || typeof book.toc !== "object") return;
  TPP.TOC_FIELDS.forEach(function (field) {
    const descriptor = Object.getOwnPropertyDescriptor(book, field);
    if (
      descriptor &&
      !descriptor.get &&
      !descriptor.set &&
      descriptor.enumerable !== false
    ) {
      delete book[field];
    }
  });
};
TPP.pageInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().page) || {};
  book.page = Object.assign({}, fallback, book.page || {});
  return book.page;
};
TPP.attachPageAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  TPP.PAGE_FIELDS.forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: function () {
        return TPP.pageInfo(book)[field];
      },
      set: function (value) {
        TPP.pageInfo(book)[field] = value;
      },
    });
  });
  return book;
};
TPP.syncPageFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const page = TPP.pageInfo(book);
  TPP.PAGE_FIELDS.forEach(function (field) {
    if (field in book) page[field] = book[field];
  });
};
TPP.compactPageInfo = function (book) {
  if (!book || !book.page || typeof book.page !== "object") return;
  TPP.PAGE_FIELDS.forEach(function (field) {
    const descriptor = Object.getOwnPropertyDescriptor(book, field);
    if (
      descriptor &&
      !descriptor.get &&
      !descriptor.set &&
      descriptor.enumerable !== false
    ) {
      delete book[field];
    }
  });
};
TPP.textInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().text) || {};
  book.text = Object.assign({}, fallback, book.text || {});
  return book.text;
};
TPP.attachTextAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  TPP.TEXT_FIELDS.forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: function () {
        return TPP.textInfo(book)[field];
      },
      set: function (value) {
        TPP.textInfo(book)[field] = value;
      },
    });
  });
  return book;
};
TPP.syncTextFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const text = TPP.textInfo(book);
  TPP.TEXT_FIELDS.forEach(function (field) {
    if (field in book) text[field] = book[field];
  });
};
TPP.compactTextInfo = function (book) {
  if (!book || !book.text || typeof book.text !== "object") return;
  TPP.TEXT_FIELDS.forEach(function (field) {
    const descriptor = Object.getOwnPropertyDescriptor(book, field);
    if (
      descriptor &&
      !descriptor.get &&
      !descriptor.set &&
      descriptor.enumerable !== false
    ) {
      delete book[field];
    }
  });
};
TPP.coverFrontInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().coverFront) || {};
  book.coverFront = Object.assign({}, fallback, book.coverFront || {});
  return book.coverFront;
};
TPP.coverFrontImageElement = function (book) {
  return TPP.findImageElement(book, "front", "cover");
};
TPP.coverTitleElement = function (book) {
  return TPP.findTextElement(book, "front", "title");
};
TPP.coverAuthorElement = function (book) {
  return TPP.findTextElement(book, "front", "author");
};
TPP.coverSeriesElement = function (book) {
  return TPP.findTextElement(book, "front", "series");
};
TPP.coverPublisherElement = function (book) {
  return TPP.findTextElement(book, "front", "publisher");
};
TPP.attachCoverFrontAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  const definitions = {
    coverImageId: {
      get: function () {
        const element = TPP.coverFrontImageElement(book);
        return (element && element.fileId) || "";
      },
      set: function (value) {
        const element = TPP.coverFrontImageElement(book);
        if (element) element.fileId = value || "";
      },
    },
    coverOverflowImage: {
      get: function () {
        return TPP.coverFrontInfo(book).overflowImage;
      },
      set: function (value) {
        TPP.coverFrontInfo(book).overflowImage = value;
      },
    },
    coverClipImageToFrame: {
      get: function () {
        return TPP.coverFrontInfo(book).clipImageToFrame;
      },
      set: function (value) {
        TPP.coverFrontInfo(book).clipImageToFrame = value;
      },
    },
    coverBg1: {
      get: function () {
        return TPP.coverFrontInfo(book).bg1;
      },
      set: function (value) {
        TPP.coverFrontInfo(book).bg1 = value;
      },
    },
    coverBg2: {
      get: function () {
        return TPP.coverFrontInfo(book).bg2;
      },
      set: function (value) {
        TPP.coverFrontInfo(book).bg2 = value;
      },
    },
    coverBorder: {
      get: function () {
        return TPP.coverFrontInfo(book).border;
      },
      set: function (value) {
        TPP.coverFrontInfo(book).border = value;
      },
    },
    coverBorderOn: {
      get: function () {
        return TPP.coverFrontInfo(book).borderOn;
      },
      set: function (value) {
        TPP.coverFrontInfo(book).borderOn = value;
      },
    },
    coverImgX: {
      get: function () {
        const element = TPP.coverFrontImageElement(book);
        return Number((element && element.x) || 0);
      },
      set: function (value) {
        const element = TPP.coverFrontImageElement(book);
        if (element) element.x = Number(value) || 0;
      },
    },
    coverImgY: {
      get: function () {
        const element = TPP.coverFrontImageElement(book);
        return Number((element && element.y) || 0);
      },
      set: function (value) {
        const element = TPP.coverFrontImageElement(book);
        if (element) element.y = Number(value) || 0;
      },
    },
    coverImgZoom: {
      get: function () {
        const element = TPP.coverFrontImageElement(book);
        return Number((element && element.zoom) || 120);
      },
      set: function (value) {
        const element = TPP.coverFrontImageElement(book);
        if (element) element.zoom = Number(value) || 120;
      },
    },
    coverImgRotate: {
      get: function () {
        const element = TPP.coverFrontImageElement(book);
        return Number((element && element.rotate) || 0);
      },
      set: function (value) {
        const element = TPP.coverFrontImageElement(book);
        if (element) element.rotate = Number(value) || 0;
      },
    },
    coverShowTitle: {
      get: function () {
        const element = TPP.coverTitleElement(book);
        return element ? element.enabled !== false : true;
      },
      set: function (value) {
        const element = TPP.coverTitleElement(book);
        if (element) element.enabled = value !== false;
      },
    },
    coverShowAuthor: {
      get: function () {
        const element = TPP.coverAuthorElement(book);
        return Boolean(element && element.enabled !== false);
      },
      set: function (value) {
        const element = TPP.coverAuthorElement(book);
        if (element) element.enabled = value !== false;
      },
    },
    coverShowSeries: {
      get: function () {
        const element = TPP.coverSeriesElement(book);
        return Boolean(element && element.enabled !== false);
      },
      set: function (value) {
        const element = TPP.coverSeriesElement(book);
        if (element) element.enabled = value !== false;
      },
    },
    coverShowPublisher: {
      get: function () {
        const element = TPP.coverPublisherElement(book);
        return Boolean(element && element.enabled !== false);
      },
      set: function (value) {
        const element = TPP.coverPublisherElement(book);
        if (element) element.enabled = value !== false;
      },
    },
    coverText: {
      get: function () {
        const element = TPP.coverTitleElement(book);
        return (element && element.color) || "#ffffff";
      },
      set: function (value) {
        [
          TPP.coverTitleElement(book),
          TPP.coverAuthorElement(book),
          TPP.coverSeriesElement(book),
          TPP.coverPublisherElement(book),
        ].forEach(function (element) {
          if (element) element.color = value || "#ffffff";
        });
      },
    },
    coverStroke: {
      get: function () {
        const element = TPP.coverTitleElement(book);
        return Math.max(0, Number((element && element.outlineSize) || 0)) > 0;
      },
      set: function (value) {
        if (value !== false) return;
        [
          TPP.coverTitleElement(book),
          TPP.coverAuthorElement(book),
          TPP.coverSeriesElement(book),
          TPP.coverPublisherElement(book),
        ].forEach(function (element) {
          if (element) element.outlineSize = 0;
        });
      },
    },
    coverStrokeColor: {
      get: function () {
        const element = TPP.coverTitleElement(book);
        return (element && element.outlineColor) || "#000000";
      },
      set: function (value) {
        [
          TPP.coverTitleElement(book),
          TPP.coverAuthorElement(book),
          TPP.coverSeriesElement(book),
          TPP.coverPublisherElement(book),
        ].forEach(function (element) {
          if (element) element.outlineColor = value || "#000000";
        });
      },
    },
    coverStrokeSize: {
      get: function () {
        const element = TPP.coverTitleElement(book);
        return Math.max(0, Number((element && element.outlineSize) || 0));
      },
      set: function (value) {
        const size = Math.max(0, Number(value) || 0);
        [
          TPP.coverTitleElement(book),
          TPP.coverAuthorElement(book),
          TPP.coverSeriesElement(book),
          TPP.coverPublisherElement(book),
        ].forEach(function (element) {
          if (element) element.outlineSize = size;
        });
      },
    },
  };
  [
    ["coverTitle", TPP.coverTitleElement],
    ["coverAuthor", TPP.coverAuthorElement],
    ["coverSeries", TPP.coverSeriesElement],
    ["coverPublisher", TPP.coverPublisherElement],
  ].forEach(function (pair) {
    const prefix = pair[0];
    const getter = pair[1];
    definitions[prefix + "Y"] = {
      get: function () {
        const element = getter(book);
        return Number((element && element.y) || 0);
      },
      set: function (value) {
        const element = getter(book);
        if (element) element.y = Number(value) || 0;
      },
    };
    definitions[prefix + "Size"] = {
      get: function () {
        const element = getter(book);
        return Number((element && element.size) || 0);
      },
      set: function (value) {
        const element = getter(book);
        if (element) element.size = Number(value) || 0;
      },
    };
    definitions[prefix + "Color"] = {
      get: function () {
        const element = getter(book);
        return (element && element.color) || "#ffffff";
      },
      set: function (value) {
        const element = getter(book);
        if (element) element.color = value || "#ffffff";
      },
    };
    definitions[prefix + "Stroke"] = {
      get: function () {
        const element = getter(book);
        return Math.max(0, Number((element && element.outlineSize) || 0)) > 0;
      },
      set: function (value) {
        const element = getter(book);
        if (element && value === false) element.outlineSize = 0;
      },
    };
    definitions[prefix + "StrokeColor"] = {
      get: function () {
        const element = getter(book);
        return (element && element.outlineColor) || "#000000";
      },
      set: function (value) {
        const element = getter(book);
        if (element) element.outlineColor = value || "#000000";
      },
    };
    definitions[prefix + "StrokeSize"] = {
      get: function () {
        const element = getter(book);
        return Math.max(0, Number((element && element.outlineSize) || 0));
      },
      set: function (value) {
        const element = getter(book);
        if (element) element.outlineSize = Math.max(0, Number(value) || 0);
      },
    };
  });
  Object.keys(definitions).forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: definitions[field].get,
      set: definitions[field].set,
    });
  });
  return book;
};
TPP.syncCoverFrontFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const coverFront = TPP.coverFrontInfo(book);
  const imageElement = TPP.coverFrontImageElement(book);
  if (imageElement && !coverFront.imageElementId)
    coverFront.imageElementId = imageElement.id || "front-cover-image";
  if ("coverOverflowImage" in book)
    coverFront.overflowImage = book.coverOverflowImage;
  if ("coverClipImageToFrame" in book)
    coverFront.clipImageToFrame = book.coverClipImageToFrame;
  if ("coverBg1" in book) coverFront.bg1 = book.coverBg1;
  if ("coverBg2" in book) coverFront.bg2 = book.coverBg2;
  if ("coverBorder" in book) coverFront.border = book.coverBorder;
  if ("coverBorderOn" in book) coverFront.borderOn = book.coverBorderOn;
};
TPP.compactCoverFrontInfo = function (book) {
  if (!book || !book.coverFront || typeof book.coverFront !== "object") return;
  TPP.COVER_FRONT_FIELDS.concat(TPP.COVER_LEGACY_FIELDS).forEach(
    function (field) {
      const descriptor = Object.getOwnPropertyDescriptor(book, field);
      if (
        descriptor &&
        !descriptor.get &&
        !descriptor.set &&
        descriptor.enumerable !== false
      ) {
        delete book[field];
      }
    },
  );
};
TPP.backCoverInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().backCover) || {};
  book.backCover = Object.assign({}, fallback, book.backCover || {});
  return book.backCover;
};
TPP.backCoverTextElement = function (book) {
  return TPP.findTextElement(book, "back", "custom");
};
TPP.backCoverImageElement = function (book) {
  return TPP.findImageElement(book, "back", "cover");
};
TPP.attachBackCoverAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  const definitions = {
    backImageId: {
      get: function () {
        const element = TPP.backCoverImageElement(book);
        return (element && element.fileId) || "";
      },
      set: function (value) {
        const element = TPP.backCoverImageElement(book);
        if (element) element.fileId = value || "";
      },
    },
    backText: {
      get: function () {
        const element = TPP.backCoverTextElement(book);
        return String((element && element.customText) || "");
      },
      set: function (value) {
        const element = TPP.backCoverTextElement(book);
        if (element) element.customText = String(value || "");
      },
    },
    backTextY: {
      get: function () {
        const element = TPP.backCoverTextElement(book);
        return Number((element && element.y) || 0);
      },
      set: function (value) {
        const element = TPP.backCoverTextElement(book);
        if (element) element.y = Number(value) || 0;
      },
    },
    backTextSize: {
      get: function () {
        const element = TPP.backCoverTextElement(book);
        return Number((element && element.size) || 0);
      },
      set: function (value) {
        const element = TPP.backCoverTextElement(book);
        if (element) element.size = Number(value) || 0;
      },
    },
    backTextColor: {
      get: function () {
        const element = TPP.backCoverTextElement(book);
        return (element && element.color) || "";
      },
      set: function (value) {
        const element = TPP.backCoverTextElement(book);
        if (element) element.color = value || "";
      },
    },
    backTextAlign: {
      get: function () {
        const element = TPP.backCoverTextElement(book);
        return (element && element.align) || "center";
      },
      set: function (value) {
        const element = TPP.backCoverTextElement(book);
        if (element) element.align = value || "center";
      },
    },
    backTextLastLine: {
      get: function () {
        return TPP.backCoverInfo(book).textLastLine;
      },
      set: function (value) {
        TPP.backCoverInfo(book).textLastLine = value || "auto";
      },
    },
    backFrameOn: {
      get: function () {
        return Boolean(TPP.backCoverInfo(book).frameOn);
      },
      set: function (value) {
        TPP.backCoverInfo(book).frameOn = Boolean(value);
      },
    },
    backClipImageToFrame: {
      get: function () {
        return Boolean(TPP.backCoverInfo(book).clipImageToFrame);
      },
      set: function (value) {
        TPP.backCoverInfo(book).clipImageToFrame = Boolean(value);
      },
    },
    backImgX: {
      get: function () {
        const element = TPP.backCoverImageElement(book);
        return Number((element && element.x) || 0);
      },
      set: function (value) {
        const element = TPP.backCoverImageElement(book);
        if (element) element.x = Number(value) || 0;
      },
    },
    backImgY: {
      get: function () {
        const element = TPP.backCoverImageElement(book);
        return Number((element && element.y) || 0);
      },
      set: function (value) {
        const element = TPP.backCoverImageElement(book);
        if (element) element.y = Number(value) || 0;
      },
    },
    backImgZoom: {
      get: function () {
        const element = TPP.backCoverImageElement(book);
        return Number((element && element.zoom) || 120);
      },
      set: function (value) {
        const element = TPP.backCoverImageElement(book);
        if (element) element.zoom = Number(value) || 120;
      },
    },
    backImgRotate: {
      get: function () {
        const element = TPP.backCoverImageElement(book);
        return Number((element && element.rotate) || 0);
      },
      set: function (value) {
        const element = TPP.backCoverImageElement(book);
        if (element) element.rotate = Number(value) || 0;
      },
    },
  };
  Object.keys(definitions).forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: definitions[field].get,
      set: definitions[field].set,
    });
  });
  return book;
};
TPP.syncBackCoverFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const back = TPP.backCoverInfo(book);
  const imageElement = TPP.backCoverImageElement(book);
  if (imageElement && !back.imageElementId)
    back.imageElementId = imageElement.id;
  if ("backTextLastLine" in book) back.textLastLine = book.backTextLastLine;
  if ("backFrameOn" in book) back.frameOn = book.backFrameOn;
  if ("backClipImageToFrame" in book)
    back.clipImageToFrame = book.backClipImageToFrame;
};
TPP.compactBackCoverInfo = function (book) {
  if (!book || !book.backCover || typeof book.backCover !== "object") return;
  Object.keys(book.backCover).forEach(function (key) {
    if (!TPP.BACK_COVER_SCHEMA_KEYS.has(key)) delete book.backCover[key];
  });
  TPP.BACK_COVER_FIELDS.forEach(function (field) {
    const descriptor = Object.getOwnPropertyDescriptor(book, field);
    if (
      descriptor &&
      !descriptor.get &&
      !descriptor.set &&
      descriptor.enumerable !== false
    ) {
      delete book[field];
    }
  });
};
TPP.spineInfo = function (book) {
  if (!book || typeof book !== "object") return {};
  const fallback = (TPP.fallbackBook && TPP.fallbackBook().spine) || {};
  book.spine = Object.assign({}, fallback, book.spine || {});
  return book.spine;
};
TPP.spineImageElement = function (book) {
  return TPP.findImageElement(book, "spine", "cover");
};
TPP.spineTitleElement = function (book) {
  return TPP.findTextElement(book, "spine", "title");
};
TPP.spineAuthorElement = function (book) {
  return TPP.findTextElement(book, "spine", "author");
};
TPP.attachSpineAccessors = function (book) {
  if (!book || typeof book !== "object") return book;
  const definitions = {
    spineImageId: {
      get: function () {
        const element = TPP.spineImageElement(book);
        return (element && element.fileId) || "";
      },
      set: function (value) {
        const element = TPP.spineImageElement(book);
        if (element) element.fileId = value || "";
      },
    },
    spineImgX: {
      get: function () {
        const element = TPP.spineImageElement(book);
        return Number((element && element.x) || 0);
      },
      set: function (value) {
        const element = TPP.spineImageElement(book);
        if (element) element.x = Number(value) || 0;
      },
    },
    spineImgY: {
      get: function () {
        const element = TPP.spineImageElement(book);
        return Number((element && element.y) || 0);
      },
      set: function (value) {
        const element = TPP.spineImageElement(book);
        if (element) element.y = Number(value) || 0;
      },
    },
    spineImgZoom: {
      get: function () {
        const element = TPP.spineImageElement(book);
        return Number((element && element.zoom) || 100);
      },
      set: function (value) {
        const element = TPP.spineImageElement(book);
        if (element) element.zoom = Number(value) || 100;
      },
    },
    spineImgRotate: {
      get: function () {
        const element = TPP.spineImageElement(book);
        return Number((element && element.rotate) || 0);
      },
      set: function (value) {
        const element = TPP.spineImageElement(book);
        if (element) element.rotate = Number(value) || 0;
      },
    },
    spineTitleSize: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return Number((element && element.size) || 0);
      },
      set: function (value) {
        const element = TPP.spineTitleElement(book);
        if (element) element.size = Number(value) || 0;
      },
    },
    spineTitleX: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return Number((element && element.x) || 50);
      },
      set: function (value) {
        const element = TPP.spineTitleElement(book);
        if (element) element.x = Number(value) || 50;
      },
    },
    spineTitleY: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return Number((element && element.y) || 0);
      },
      set: function (value) {
        const element = TPP.spineTitleElement(book);
        if (element) element.y = Number(value) || 0;
      },
    },
    spineTitleWidth: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return Number((element && element.width) || 100);
      },
      set: function (value) {
        const element = TPP.spineTitleElement(book);
        if (element) {
          element.width = Math.max(10, Math.min(100, Number(value) || 100));
        }
      },
    },
    spineTitleAlign: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return (element && element.align) || "left";
      },
      set: function (value) {
        const element = TPP.spineTitleElement(book);
        if (element) element.align = value || "left";
      },
    },
    spineAuthorSize: {
      get: function () {
        const element = TPP.spineAuthorElement(book);
        return Number((element && element.size) || 0);
      },
      set: function (value) {
        const element = TPP.spineAuthorElement(book);
        if (element) element.size = Number(value) || 0;
      },
    },
    spineTextColor: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return (element && element.color) || "";
      },
      set: function (value) {
        const title = TPP.spineTitleElement(book);
        const author = TPP.spineAuthorElement(book);
        if (title) title.color = value || "";
        if (author) author.color = value || "";
      },
    },
    spineStroke: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return Boolean(Number((element && element.outlineSize) || 0) > 0);
      },
      set: function (value) {
        const title = TPP.spineTitleElement(book);
        const author = TPP.spineAuthorElement(book);
        if (!value) {
          if (title) title.outlineSize = 0;
          if (author) author.outlineSize = 0;
        }
      },
    },
    spineStrokeColor: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return (element && element.outlineColor) || "";
      },
      set: function (value) {
        const title = TPP.spineTitleElement(book);
        const author = TPP.spineAuthorElement(book);
        if (title) title.outlineColor = value || "";
        if (author) author.outlineColor = value || "";
      },
    },
    spineStrokeSize: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return Math.max(0, Number((element && element.outlineSize) || 0));
      },
      set: function (value) {
        const title = TPP.spineTitleElement(book);
        const author = TPP.spineAuthorElement(book);
        const size = Math.max(0, Number(value) || 0);
        if (title) title.outlineSize = size;
        if (author) author.outlineSize = size;
      },
    },
    spineTitleRotate: {
      get: function () {
        const element = TPP.spineTitleElement(book);
        return element ? element.rotate !== false : true;
      },
      set: function (value) {
        const element = TPP.spineTitleElement(book);
        if (element) element.rotate = value !== false;
      },
    },
    spineAuthorOn: {
      get: function () {
        const element = TPP.spineAuthorElement(book);
        return element ? element.enabled !== false : true;
      },
      set: function (value) {
        const element = TPP.spineAuthorElement(book);
        if (element) element.enabled = value !== false;
      },
    },
    spineAuthorRotate: {
      get: function () {
        const element = TPP.spineAuthorElement(book);
        return Boolean(element && element.rotate);
      },
      set: function (value) {
        const element = TPP.spineAuthorElement(book);
        if (element) element.rotate = Boolean(value);
      },
    },
  };
  Object.keys(definitions).forEach(function (field) {
    const existing = Object.getOwnPropertyDescriptor(book, field);
    if (
      existing &&
      existing.get &&
      existing.set &&
      existing.enumerable === false
    )
      return;
    Object.defineProperty(book, field, {
      configurable: true,
      enumerable: false,
      get: definitions[field].get,
      set: definitions[field].set,
    });
  });
  return book;
};
TPP.syncSpineFromLegacyFields = function (book) {
  if (!book || typeof book !== "object") return;
  const spine = TPP.spineInfo(book);
  const imageElement = TPP.spineImageElement(book);
  if (imageElement && !spine.imageElementId)
    spine.imageElementId = imageElement.id;
};
TPP.compactSpineInfo = function (book) {
  if (!book || !book.spine || typeof book.spine !== "object") return;
  Object.keys(book.spine).forEach(function (key) {
    if (!TPP.SPINE_SCHEMA_KEYS.has(key)) delete book.spine[key];
  });
  TPP.SPINE_FIELDS.forEach(function (field) {
    const descriptor = Object.getOwnPropertyDescriptor(book, field);
    if (
      descriptor &&
      !descriptor.get &&
      !descriptor.set &&
      descriptor.enumerable !== false
    ) {
      delete book[field];
    }
  });
};
TPP.bookMeta = function (book) {
  if (!book || typeof book !== "object") return {};
  book.meta = Object.assign({}, book.meta || {});
  return book.meta;
};
TPP.bookId = function (book) {
  return TPP.bookMeta(book).id || "";
};
TPP.bookRevision = function (book) {
  return Math.max(1, Math.floor(Number(TPP.bookMeta(book).revision) || 1));
};
TPP.bookSubrevision = function (book) {
  return Math.max(0, Math.floor(Number(TPP.bookMeta(book).subrevision) || 0));
};
TPP.bookProvenance = function (book) {
  const meta = TPP.bookMeta(book);
  return Array.isArray(meta.provenance) ? meta.provenance : [];
};
TPP.bookCreatedAt = function (book) {
  return TPP.bookMeta(book).createdAt || "";
};
TPP.bookUpdatedAt = function (book) {
  return TPP.bookMeta(book).updatedAt || "";
};
TPP.bookLastExportedAt = function (book) {
  return TPP.bookMeta(book).lastExportedAt || "";
};
TPP.bookLastImportedAt = function (book) {
  return TPP.bookMeta(book).lastImportedAt || "";
};
TPP.bookCoverPreviewImageId = function (book) {
  return TPP.bookMeta(book).coverPreviewImageId || "";
};
TPP.bookPageCount = function (book) {
  const count = Number(TPP.bookMeta(book).pageCount);
  return Number.isFinite(count) && count > 0 ? count : 0;
};
TPP.bookRevisionLabel = function (book) {
  const revision = TPP.bookRevision(book);
  const subrevision = TPP.bookSubrevision(book);
  return subrevision ? revision + "." + subrevision : String(revision);
};
TPP.compactBookMeta = function (book) {
  if (!book || !book.meta || typeof book.meta !== "object") return;
  const meta = book.meta;
  if (!meta.subrevision) delete meta.subrevision;
  if (!meta.lastExportedAt) delete meta.lastExportedAt;
  if (!meta.lastImportedAt) delete meta.lastImportedAt;
  if (!Array.isArray(meta.provenance) || !meta.provenance.length)
    delete meta.provenance;
};
TPP.bookExportName = function (book) {
  if (!book) return "book.json";
  if (TPP.active && TPP.bookId(book) === TPP.bookId(TPP.active) && TPP.sync)
    TPP.sync("nosave");
  const title = (book.title || "").trim();
  return (title || "book") + ".json";
};
TPP.hashString = function (value) {
  let hash = 2166136261;
  const text = String(value || "");
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return ("0000000" + (hash >>> 0).toString(16)).slice(-8);
};
TPP.fileAsset = function (book, id) {
  const files = Array.isArray(book && book.files) ? book.files : [];
  return (
    files.find(function (file) {
      return file && file.id === id;
    }) || null
  );
};
TPP.filePickerAssets = function (book) {
  const files = Array.isArray(book && book.files) ? book.files : [];
  return files.filter(function (file) {
    return file && !file.hiddenFromPicker;
  });
};
TPP.fileData = function (book, id) {
  const file = TPP.fileAsset(book, id);
  return file && file.data ? file.data : "";
};
TPP.fileFieldRefs = function (book) {
  const refs = {};
  const push = function (fileId, ref) {
    if (!fileId) return;
    refs[fileId] = refs[fileId] || [];
    refs[fileId].push(ref);
  };
  (Array.isArray(book && book.imageElements) ? book.imageElements : []).forEach(
    function (element) {
      if (!element || !element.fileId) return;
      let label = "Image";
      if (element.location === "front") label = "Front Cover Image";
      else if (element.location === "back") label = "Back Cover Image";
      else if (element.location === "spine") label = "Spine Image";
      else if (element.location === "chapter") {
        const chapter = ((book && book.chapters) || []).find(function (entry) {
          return entry && entry.id === element.part;
        });
        label =
          'Chapter Image: "' + ((chapter && chapter.title) || "Untitled") + '"';
      }
      push(element.fileId, {
        key:
          "imageElement:" +
          (element.id || TPP.imageElementKey(element.location, element.part)),
        label: label,
        imageElementId: element.id || "",
        location: element.location || "",
        part: element.part || "",
      });
    },
  );
  (Array.isArray(book && book.chapters) ? book.chapters : []).forEach(
    function (chapter, index) {
      if (!chapter || !chapter.imageId) return;
      if (
        (refs[chapter.imageId] || []).some(function (ref) {
          return ref.chapterId === chapter.id;
        })
      )
        return;
      push(chapter.imageId, {
        key: "chapter:" + (chapter && chapter.id ? chapter.id : index),
        label:
          'Chapter Image: "' +
          ((chapter && chapter.title) || "Chapter " + (index + 1)) +
          '"',
        chapterId: chapter && chapter.id ? chapter.id : "",
        chapterIndex: index,
      });
    },
  );
  return refs;
};
TPP.fileReferences = function (book, fileId) {
  const refs = TPP.fileFieldRefs(book);
  return refs[fileId] || [];
};
TPP.upsertFileAsset = function (book, data, type, name, options) {
  if (!book) return "";
  if (!Array.isArray(book.files)) book.files = [];
  const assetData = String(data || "").trim();
  if (!assetData) return "";
  const assetType =
    type ||
    (assetData.match(/^data:([^;,]+)/) || [])[1] ||
    "application/octet-stream";
  const hash = TPP.hashString(assetType + ":" + assetData);
  const meta = options || {};
  const existing = book.files.find(function (file) {
    return (
      file &&
      file.hash === hash &&
      file.data === assetData &&
      (file.role || "") === (meta.role || "")
    );
  });
  if (existing) return existing.id;
  const id = TPP.uid();
  book.files.push({
    id: id,
    type: assetType,
    name: name || "",
    data: assetData,
    hash: hash,
    role: meta.role || "",
    hiddenFromPicker: Boolean(meta.hiddenFromPicker),
  });
  return id;
};
TPP.setCoverPreviewAsset = function (book, data) {
  if (!book) return "";
  const meta = TPP.bookMeta(book);
  const assetData = String(data || "").trim();
  if (!assetData) {
    book.coverPreview = "";
    meta.coverPreviewImageId = "";
    return "";
  }
  const existing = meta.coverPreviewImageId
    ? TPP.fileAsset(book, meta.coverPreviewImageId)
    : null;
  const type = (assetData.match(/^data:([^;,]+)/) || [])[1] || "image/jpeg";
  const hash = TPP.hashString(type + ":" + assetData);
  if (existing) {
    existing.type = type;
    existing.name = "Generated Cover Preview";
    existing.data = assetData;
    existing.hash = hash;
    existing.role = "coverPreview";
    existing.hiddenFromPicker = true;
    book.coverPreview = assetData;
    return existing.id;
  }
  const id = TPP.upsertFileAsset(
    book,
    assetData,
    type,
    "Generated Cover Preview",
    {
      role: "coverPreview",
      hiddenFromPicker: true,
    },
  );
  meta.coverPreviewImageId = id;
  book.coverPreview = assetData;
  return id;
};
TPP.syncCoverPreviewAsset = function (book) {
  if (!book) return;
  const meta = TPP.bookMeta(book);
  if (book.coverPreview && !meta.coverPreviewImageId) {
    TPP.setCoverPreviewAsset(book, book.coverPreview);
    return;
  }
  const file = meta.coverPreviewImageId
    ? TPP.fileAsset(book, meta.coverPreviewImageId)
    : null;
  if (file) {
    file.role = "coverPreview";
    file.hiddenFromPicker = true;
    if (!file.name) file.name = "Generated Cover Preview";
    book.coverPreview = file.data || "";
  } else {
    book.coverPreview = "";
    meta.coverPreviewImageId = "";
  }
};
TPP.removeFileAsset = function (book, fileId) {
  if (!book || !Array.isArray(book.files) || !fileId) return false;
  if (TPP.fileReferences(book, fileId).length) return false;
  const before = book.files.length;
  book.files = book.files.filter(function (file) {
    return !file || file.id !== fileId;
  });
  return book.files.length !== before;
};
TPP.migrateInlineImage = function (book, sourceKey, targetKey) {
  if (!book) return;
  const data = String(book[sourceKey] || "").trim();
  if (data && !book[targetKey])
    book[targetKey] = TPP.upsertFileAsset(book, data);
  delete book[sourceKey];
};
TPP.migrateChapterInlineImage = function (book, chapter) {
  if (!book || !chapter) return;
  const data = String(chapter.imageData || "").trim();
  if (data && !chapter.imageId)
    chapter.imageId = TPP.upsertFileAsset(book, data);
  delete chapter.imageData;
};
TPP.normalizeFiles = function (book) {
  if (!book) return;
  book.files = Array.isArray(book.files) ? book.files : [];
  const seen = new Map();
  const idMap = {};
  book.files = book.files.reduce(function (list, file) {
    if (!file || !file.data) return list;
    const normalized = {
      id: file.id || TPP.uid(),
      type:
        file.type ||
        (String(file.data).match(/^data:([^;,]+)/) || [])[1] ||
        "application/octet-stream",
      name: file.name || "",
      data: file.data,
      hash: file.hash || TPP.hashString((file.type || "") + ":" + file.data),
      role: file.role || "",
      hiddenFromPicker: Boolean(file.hiddenFromPicker),
    };
    const key = normalized.hash + "::" + normalized.data;
    if (seen.has(key)) {
      idMap[normalized.id] = seen.get(key);
      return list;
    }
    seen.set(key, normalized.id);
    idMap[normalized.id] = normalized.id;
    list.push(normalized);
    return list;
  }, []);
  TPP.migrateInlineImage(book, "coverImageData", "coverImageId");
  TPP.migrateInlineImage(book, "backImageData", "backImageId");
  TPP.migrateInlineImage(book, "spineImageData", "spineImageId");
  ["coverImageId", "backImageId", "spineImageId"].forEach(function (key) {
    if (book[key] && idMap[book[key]]) book[key] = idMap[book[key]];
  });
  (Array.isArray(book.imageElements) ? book.imageElements : []).forEach(
    function (element) {
      if (element && element.fileId && idMap[element.fileId])
        element.fileId = idMap[element.fileId];
    },
  );
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      if (chapter && chapter.imageId && idMap[chapter.imageId])
        chapter.imageId = idMap[chapter.imageId];
    },
  );
};
TPP.esc = function (value) {
  return String(value ?? "").replace(/[&<>"']/g, function (ch) {
    return {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;",
    }[ch];
  });
};
TPP.signatureSize = function (value) {
  const fallback = 16;
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(4, Math.min(64, Math.round(n / 4) * 4)) || fallback;
};
TPP.sewingStations = function (value) {
  const n = Math.round(Number(value) || 0);
  return Math.max(2, Math.min(5, n || 3));
};
TPP.opacity = function (value, fallback) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(0, Math.min(1, n));
};
TPP.dpi = function (value) {
  const n = Math.round(Number(value) || 0);
  return Math.max(72, Math.min(1200, n || 300));
};
TPP.mediaCaptionSize = function (value, fallback) {
  const n = Number(value);
  const base = Number(fallback) || 3;
  if (!Number.isFinite(n)) return base;
  return Math.max(2, Math.min(12, n));
};
TPP.bookFingerprint = function (book) {
  const copy = TPP.clone(book || {});
  delete copy.schemaVersion;
  delete copy.coverPreview;
  delete copy.id;
  delete copy.revision;
  delete copy.subrevision;
  delete copy.provenance;
  delete copy.createdAt;
  delete copy.updatedAt;
  delete copy.lastExportedAt;
  delete copy.lastImportedAt;
  delete copy.coverPreviewId;
  delete copy._pageCount;
  if (copy.meta && typeof copy.meta === "object") delete copy.meta.pageCount;
  delete copy.coverPreviewImageId;
  delete copy.meta;
  TPP.BOOK_INFO_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.PAGE_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.TEXT_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.COVER_FRONT_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.COVER_LEGACY_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.BACK_COVER_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.SPINE_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  TPP.TOC_FIELDS.forEach(function (field) {
    delete copy[field];
  });
  copy.files = (Array.isArray(copy.files) ? copy.files : []).filter(
    function (file) {
      return file && file.role !== "coverPreview";
    },
  );
  return JSON.stringify(copy);
};
TPP.hydrateBookDates = function (book) {
  const now = TPP.nowIso();
  const fallbackMeta = (TPP.fallbackBook && TPP.fallbackBook().meta) || {};
  TPP.syncBookInfoFromLegacyFields(book);
  TPP.attachBookInfoAccessors(book);
  TPP.syncPageFromLegacyFields(book);
  TPP.attachPageAccessors(book);
  TPP.syncTextFromLegacyFields(book);
  TPP.attachTextAccessors(book);
  TPP.syncCoverFrontFromLegacyFields(book);
  TPP.attachCoverFrontAccessors(book);
  TPP.syncBackCoverFromLegacyFields(book);
  TPP.attachBackCoverAccessors(book);
  TPP.syncSpineFromLegacyFields(book);
  TPP.attachSpineAccessors(book);
  TPP.syncTocFromLegacyFields(book);
  TPP.attachTocAccessors(book);
  if (
    !Number.isFinite(Number(book.schemaVersion)) ||
    Number(book.schemaVersion) < 1
  )
    book.schemaVersion = 1;
  book.schemaVersion = Math.max(1, Math.floor(Number(book.schemaVersion) || 1));
  const meta = Object.assign({}, fallbackMeta, book.meta || {});
  if (book.id && !meta.id) meta.id = book.id;
  if ("revision" in book && !("revision" in (book.meta || {})))
    meta.revision = book.revision;
  if ("subrevision" in book && !("subrevision" in (book.meta || {})))
    meta.subrevision = book.subrevision;
  if (!Array.isArray(meta.provenance) && Array.isArray(book.provenance))
    meta.provenance = TPP.clone(book.provenance);
  if (!Array.isArray(meta.provenance) && Array.isArray(book.ancestry))
    meta.provenance = TPP.clone(book.ancestry);
  if ("createdAt" in book && !meta.createdAt) meta.createdAt = book.createdAt;
  if ("updatedAt" in book && !meta.updatedAt) meta.updatedAt = book.updatedAt;
  if ("lastExportedAt" in book && !("lastExportedAt" in (book.meta || {})))
    meta.lastExportedAt = book.lastExportedAt;
  if ("lastImportedAt" in book && !("lastImportedAt" in (book.meta || {})))
    meta.lastImportedAt = book.lastImportedAt;
  if ("coverPreviewId" in book && !meta.coverPreviewImageId)
    meta.coverPreviewImageId = book.coverPreviewId;
  if ("coverPreviewImageId" in book && !meta.coverPreviewImageId)
    meta.coverPreviewImageId = book.coverPreviewImageId;
  if ("_pageCount" in book && !("pageCount" in (book.meta || {})))
    meta.pageCount = book._pageCount;
  if (book.meta && "_pageCount" in book.meta && !("pageCount" in book.meta))
    meta.pageCount = book.meta._pageCount;
  if (!meta.id) meta.id = TPP.uid();
  if (!Number.isFinite(Number(meta.revision)) || Number(meta.revision) < 1)
    meta.revision = 1;
  meta.revision = Math.max(1, Math.floor(Number(meta.revision) || 1));
  if (
    !Number.isFinite(Number(meta.subrevision)) ||
    Number(meta.subrevision) < 0
  )
    meta.subrevision = 0;
  meta.subrevision = Math.max(0, Math.floor(Number(meta.subrevision) || 0));
  if (!Array.isArray(meta.provenance)) meta.provenance = [];
  delete book.ancestry;
  if (!meta.createdAt && meta.updatedAt) meta.createdAt = meta.updatedAt;
  if (!meta.createdAt) meta.createdAt = now;
  if (!meta.updatedAt) meta.updatedAt = meta.createdAt;
  if (!("lastExportedAt" in meta)) meta.lastExportedAt = "";
  if (!("lastImportedAt" in meta)) meta.lastImportedAt = "";
  if (!("coverPreviewImageId" in meta)) meta.coverPreviewImageId = "";
  meta.pageCount = Math.max(0, Math.floor(Number(meta.pageCount) || 0));
  delete meta._pageCount;
  book.meta = meta;
  [
    "id",
    "revision",
    "subrevision",
    "provenance",
    "createdAt",
    "updatedAt",
    "lastExportedAt",
    "lastImportedAt",
    "coverPreviewId",
    "coverPreviewImageId",
    "_pageCount",
    "imageExportDpi",
  ].forEach(function (key) {
    delete book[key];
  });
  TPP.compactBookInfo(book);
  TPP.compactPageInfo(book);
  TPP.compactTextInfo(book);
  TPP.compactCoverFrontInfo(book);
  TPP.compactBackCoverInfo(book);
  TPP.compactSpineInfo(book);
  TPP.compactTocInfo(book);
  TPP.compactBookMeta(book);
  book.schemaVersion = TPP.SCHEMA_VERSION;
  return book;
};
TPP.unwrapImportPayload = function (data) {
  if (!data || typeof data !== "object") return { kind: "book", value: data };
  if (Array.isArray(data.books))
    return {
      kind: "library",
      value: data.books,
      schemaVersion: Number(data.schemaVersion) || 1,
    };
  if (data.book && typeof data.book === "object")
    return {
      kind: "book",
      value: data.book,
      schemaVersion:
        Number(data.schemaVersion) || Number(data.book.schemaVersion) || 1,
    };
  if (data.style && typeof data.style === "object")
    return {
      kind: "style",
      value: data.style,
      schemaVersion: Number(data.schemaVersion) || 1,
    };
  return {
    kind: "book",
    value: data,
    schemaVersion: Number(data.schemaVersion) || 1,
  };
};
TPP.bookSourceEntry = function (book, action, stamp) {
  const when = stamp || TPP.nowIso();
  return {
    action: action || "copy",
    sourceId: TPP.bookId(book),
    sourceTitle: book && book.title ? book.title : "",
    sourceRevision: TPP.bookRevision(book),
    sourceSubrevision: TPP.bookSubrevision(book),
    sourceUpdatedAt: TPP.bookUpdatedAt(book) || when,
    sourceCreatedAt: TPP.bookCreatedAt(book) || when,
    recordedAt: when,
  };
};
TPP.combineProvenance = function (a, b) {
  const seen = new Set();
  return (Array.isArray(a) ? a : [])
    .concat(Array.isArray(b) ? b : [])
    .filter(function (entry) {
      const key = JSON.stringify(entry || {});
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
};
TPP.bookDescendant = function (source, overrides, action, stamp) {
  const when = stamp || TPP.nowIso();
  const descendant = TPP.norm(
    Object.assign({}, TPP.clone(source || {}), overrides || {}),
  );
  const meta = TPP.bookMeta(descendant);
  meta.id = (overrides && overrides.id) || meta.id || TPP.uid();
  meta.revision = 1;
  meta.subrevision = 0;
  meta.createdAt = when;
  meta.updatedAt = when;
  meta.lastExportedAt = "";
  meta.lastImportedAt = action === "import" ? when : "";
  meta.provenance = Array.isArray(TPP.bookProvenance(source))
    ? TPP.clone(TPP.bookProvenance(source))
    : [];
  meta.provenance.push(TPP.bookSourceEntry(source, action, when));
  return descendant;
};
TPP.bookImported = function (source, stamp) {
  const when = stamp || TPP.nowIso();
  const imported = TPP.norm(TPP.clone(source || {}));
  const meta = TPP.bookMeta(imported);
  meta.lastImportedAt = when;
  meta.provenance = TPP.combineProvenance(TPP.bookProvenance(imported), [
    TPP.bookSourceEntry(source, "import", when),
  ]);
  return imported;
};
TPP.mergeImportedBook = function (existing, incoming, stamp) {
  const when = stamp || TPP.nowIso();
  const merged = TPP.norm(
    Object.assign({}, TPP.clone(existing || {}), TPP.clone(incoming || {})),
  );
  const meta = TPP.bookMeta(merged);
  meta.id = TPP.bookId(existing) || meta.id;
  meta.createdAt = TPP.bookCreatedAt(existing) || meta.createdAt;
  meta.updatedAt = TPP.bookUpdatedAt(incoming) || meta.updatedAt;
  meta.revision = Math.max(
    1,
    TPP.bookRevision(existing),
    TPP.bookRevision(incoming),
  );
  meta.subrevision = 0;
  meta.lastImportedAt = when;
  meta.lastExportedAt =
    TPP.bookLastExportedAt(existing) || TPP.bookLastExportedAt(incoming) || "";
  meta.provenance = TPP.combineProvenance(
    TPP.combineProvenance(
      TPP.bookProvenance(existing),
      TPP.bookProvenance(incoming),
    ),
    [TPP.bookSourceEntry(incoming, "import", when)],
  );
  return merged;
};
TPP.resolveImportConflict = function (incoming, existing) {
  return Promise.resolve("cancel");
};
TPP.markBookExported = function (book, stamp) {
  if (!book) return;
  TPP.bookMeta(book).lastExportedAt = stamp || TPP.nowIso();
};
TPP.markBookImported = function (book, stamp) {
  if (!book) return;
  TPP.bookMeta(book).lastImportedAt = stamp || TPP.nowIso();
};
TPP.imageElementKey = function (location, part) {
  return String(location || "") + ":" + String(part || "");
};
TPP.findImageElement = function (book, location, part) {
  const key = TPP.imageElementKey(location, part);
  const list = Array.isArray(book && book.imageElements)
    ? book.imageElements
    : [];
  return (
    list.find(function (entry) {
      return (
        TPP.imageElementKey(entry && entry.location, entry && entry.part) ===
        key
      );
    }) || null
  );
};
TPP.findChapterImageElement = function (book, chapter) {
  if (!book || !chapter) return null;
  const list = Array.isArray(book.imageElements) ? book.imageElements : [];
  if (chapter.imageElementId) {
    const byId = list.find(function (entry) {
      return entry && entry.id === chapter.imageElementId;
    });
    if (byId) return byId;
  }
  return TPP.findImageElement(book, "chapter", chapter.id);
};
TPP.defaultImageElements = function (book, base) {
  const source = book || {};
  const fallback = base || source || {};
  const sourceBack = source.backCover || {};
  const sourceSpine = source.spine || {};
  return [
    {
      id: "front-cover-image",
      location: "front",
      part: "cover",
      fileId: source.coverImageId || fallback.coverImageId || "",
      x: Number(source.coverImgX) || 0,
      y: Number(source.coverImgY) || 0,
      zoom: Number(source.coverImgZoom) || Number(fallback.coverImgZoom) || 120,
      rotate: Number(source.coverImgRotate) || 0,
      placement: "cover",
    },
    {
      id: "back-cover-image",
      location: "back",
      part: "cover",
      fileId: source.backImageId || fallback.backImageId || "",
      x: Number(source.backImgX ?? sourceBack.imgX) || 0,
      y: Number(source.backImgY ?? sourceBack.imgY) || 0,
      zoom:
        Number(source.backImgZoom ?? sourceBack.imgZoom) ||
        Number(fallback.backImgZoom) ||
        120,
      rotate: Number(source.backImgRotate ?? sourceBack.imgRotate) || 0,
      placement: "cover",
    },
    {
      id: "spine-image",
      location: "spine",
      part: "cover",
      fileId: source.spineImageId || fallback.spineImageId || "",
      x: Number(source.spineImgX ?? sourceSpine.imgX) || 0,
      y: Number(source.spineImgY ?? sourceSpine.imgY) || 0,
      zoom:
        Number(source.spineImgZoom ?? sourceSpine.imgZoom) ||
        Number(fallback.spineImgZoom) ||
        100,
      rotate: Number(source.spineImgRotate ?? sourceSpine.imgRotate) || 0,
      placement: "cover",
    },
  ];
};
TPP.ensureChapterImageElements = function (book) {
  if (!book) return;
  book.imageElements = Array.isArray(book.imageElements)
    ? book.imageElements
    : [];
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      if (!chapter) return;
      let element = TPP.findChapterImageElement(book, chapter);
      if (!element) {
        element = {
          id: TPP.uid(),
          location: "chapter",
          part: chapter.id,
          fileId: chapter.imageId || "",
          x: 0,
          y: 0,
          zoom: Math.min(
            100,
            Math.max(10, Number(chapter.imageZoom || chapter.imageWidth) || 70),
          ),
          rotate: Number(chapter.imageRotate) || 0,
          placement: chapter.imagePlacement || "none",
        };
        book.imageElements.push(element);
      }
      if (!element.id) element.id = TPP.uid();
      element.location = "chapter";
      element.part = chapter.id;
      chapter.imageElementId = element.id;
    },
  );
  const chapterIds = new Set(
    (Array.isArray(book.chapters) ? book.chapters : []).map(function (chapter) {
      return chapter && chapter.id;
    }),
  );
  book.imageElements = book.imageElements.filter(function (element) {
    return (
      (element && element.location !== "chapter") ||
      chapterIds.has(element && element.part)
    );
  });
};
TPP.migrateImageElements = function (book, base) {
  const defaults = TPP.defaultImageElements(book, base);
  const existing = Array.isArray(book.imageElements) ? book.imageElements : [];
  const byKey = new Map(
    existing.map(function (entry) {
      return [
        TPP.imageElementKey(entry && entry.location, entry && entry.part),
        entry,
      ];
    }),
  );
  const chapterElements = existing.filter(function (entry) {
    return entry && entry.location === "chapter";
  });
  book.imageElements = defaults
    .map(function (entry) {
      return Object.assign(
        {},
        entry,
        byKey.get(TPP.imageElementKey(entry.location, entry.part)) || {},
      );
    })
    .concat(chapterElements);
  TPP.ensureChapterImageElements(book);
};
TPP.syncLegacyImageFieldsFromElements = function (book) {
  const front = TPP.findImageElement(book, "front", "cover");
  const back = TPP.findImageElement(book, "back", "cover");
  const spine = TPP.findImageElement(book, "spine", "cover");
  if (front) {
    TPP.coverFrontInfo(book).imageElementId = front.id || "front-cover-image";
  }
  if (back) {
    book.backImageId = back.fileId || "";
    TPP.backCoverInfo(book).imageElementId = back.id || "back-cover-image";
  }
  if (spine) {
    book.spineImageId = spine.fileId || "";
    TPP.spineInfo(book).imageElementId = spine.id || "spine-image";
  }
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      const element = TPP.findChapterImageElement(book, chapter);
      if (!element) return;
      chapter.imageElementId = element.id || "";
      chapter.imageId = element.fileId || "";
      chapter.imagePlacement = element.placement || "none";
      chapter.imageZoom = Math.min(
        100,
        Math.max(10, Number(element.zoom) || 70),
      );
      chapter.imageRotate = Number(element.rotate) || 0;
    },
  );
};
TPP.syncImageElementsFromLegacyFields = function (book) {
  const front = TPP.findImageElement(book, "front", "cover");
  const back = TPP.findImageElement(book, "back", "cover");
  const spine = TPP.findImageElement(book, "spine", "cover");
  if (front)
    Object.assign(front, {
      fileId: book.coverImageId || "",
      x: Number(book.coverImgX) || 0,
      y: Number(book.coverImgY) || 0,
      zoom: Number(book.coverImgZoom) || 120,
      rotate: Number(book.coverImgRotate) || 0,
      placement: "cover",
    });
  if (back)
    Object.assign(back, {
      fileId: book.backImageId || "",
      x: Number(book.backImgX) || 0,
      y: Number(book.backImgY) || 0,
      zoom: Number(book.backImgZoom) || 120,
      rotate: Number(book.backImgRotate) || 0,
      placement: "cover",
    });
  if (spine)
    Object.assign(spine, {
      fileId: book.spineImageId || "",
      x: Number(book.spineImgX) || 0,
      y: Number(book.spineImgY) || 0,
      zoom: Number(book.spineImgZoom) || 100,
      rotate: Number(book.spineImgRotate) || 0,
      placement: "cover",
    });
  if (front)
    TPP.coverFrontInfo(book).imageElementId = front.id || "front-cover-image";
  if (back)
    TPP.backCoverInfo(book).imageElementId = back.id || "back-cover-image";
  if (spine) TPP.spineInfo(book).imageElementId = spine.id || "spine-image";
  (Array.isArray(book.chapters) ? book.chapters : []).forEach(
    function (chapter) {
      const element = TPP.findChapterImageElement(book, chapter);
      if (!element) return;
      element.fileId = chapter.imageId || element.fileId || "";
      element.zoom = Math.min(
        100,
        Math.max(10, Number(chapter.imageZoom || chapter.imageWidth) || 70),
      );
      element.rotate = Number(chapter.imageRotate) || 0;
      element.placement = chapter.imagePlacement || "none";
      chapter.imageElementId = element.id || "";
    },
  );
};
TPP.textElementKey = function (location, part) {
  return String(location || "") + ":" + String(part || "");
};
TPP.findTextElement = function (book, location, part) {
  const key = TPP.textElementKey(location, part);
  const list = Array.isArray(book && book.textElements)
    ? book.textElements
    : [];
  return (
    list.find(function (entry) {
      return (
        TPP.textElementKey(entry && entry.location, entry && entry.part) === key
      );
    }) || null
  );
};
TPP.defaultTextElements = function (book, base) {
  const source = book || {};
  const fallback = base || source || {};
  const sourceBack = source.backCover || {};
  const sourceSpine = source.spine || {};
  const sharedColor = source.coverText || fallback.coverText || "#ffffff";
  const sharedStrokeColor =
    source.coverStrokeColor || fallback.coverStrokeColor || "#000000";
  const sharedStrokeSize = Number.isFinite(Number(source.coverStrokeSize))
    ? Number(source.coverStrokeSize)
    : Number(fallback.coverStrokeSize) || 0;
  return [
    {
      id: "front-cover-title",
      location: "front",
      part: "title",
      enabled: source.coverShowTitle !== false,
      size:
        Number(source.coverTitleSize) || Number(fallback.coverTitleSize) || 8,
      x: 0,
      y: Number(source.coverTitleY) || Number(fallback.coverTitleY) || 12,
      width: 100,
      align: "center",
      color: source.coverTitleColor || sharedColor,
      outlineColor: source.coverTitleStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverTitleStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      id: "front-cover-author",
      location: "front",
      part: "author",
      enabled: Boolean(source.coverShowAuthor),
      size:
        Number(source.coverAuthorSize) ||
        Number(source.coverMetaSize) ||
        Number(fallback.coverAuthorSize) ||
        4.2,
      x: 0,
      y: Number(source.coverAuthorY) || Number(fallback.coverAuthorY) || 72,
      width: 100,
      align: "center",
      color: source.coverAuthorColor || sharedColor,
      outlineColor: source.coverAuthorStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverAuthorStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      id: "front-cover-series",
      location: "front",
      part: "series",
      enabled: Boolean(source.coverShowSeries),
      size:
        Number(source.coverSeriesSize) ||
        Number(source.coverMetaSize) ||
        Number(fallback.coverSeriesSize) ||
        4.2,
      x: 0,
      y: Number(source.coverSeriesY) || Number(fallback.coverSeriesY) || 6,
      width: 100,
      align: "center",
      color: source.coverSeriesColor || sharedColor,
      outlineColor: source.coverSeriesStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverSeriesStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      id: "front-cover-publisher",
      location: "front",
      part: "publisher",
      enabled: Boolean(source.coverShowPublisher),
      size:
        Number(source.coverPublisherSize) ||
        Number(source.coverMetaSize) ||
        Number(fallback.coverPublisherSize) ||
        4.2,
      x: 0,
      y:
        Number(source.coverPublisherY) ||
        Number(fallback.coverPublisherY) ||
        84,
      width: 100,
      align: "center",
      color: source.coverPublisherColor || sharedColor,
      outlineColor: source.coverPublisherStrokeColor || sharedStrokeColor,
      outlineSize: Number(source.coverPublisherStrokeSize) || sharedStrokeSize,
      rotate: false,
      customText: "",
    },
    {
      id: "back-cover-text",
      location: "back",
      part: "custom",
      enabled: true,
      size:
        Number(source.backTextSize ?? sourceBack.textSize) ||
        Number(fallback.backTextSize) ||
        4.5,
      x: 50,
      y:
        Number(source.backTextY ?? sourceBack.textY) ||
        Number(fallback.backTextY) ||
        76,
      width: 100,
      align:
        source.backTextAlign ||
        sourceBack.textAlign ||
        fallback.backTextAlign ||
        "center",
      color:
        source.backTextColor ||
        sourceBack.textColor ||
        fallback.backTextColor ||
        "#ffffff",
      outlineColor: "#000000",
      outlineSize: 0,
      rotate: false,
      customText: source.backText || sourceBack.text || fallback.backText || "",
    },
    {
      id: "spine-title",
      location: "spine",
      part: "title",
      enabled: true,
      size:
        Number(source.spineTitleSize ?? sourceSpine.titleSize) ||
        Number(fallback.spineTitleSize) ||
        5,
      x:
        Number(source.spineTitleX ?? sourceSpine.titleX) ||
        Number(fallback.spineTitleX) ||
        50,
      y:
        Number(source.spineTitleY ?? sourceSpine.titleY) ||
        Number(fallback.spineTitleY) ||
        4,
      width:
        Number(source.spineTitleWidth ?? sourceSpine.titleWidth) ||
        Number(fallback.spineTitleWidth) ||
        100,
      align:
        source.spineTitleAlign ||
        sourceSpine.titleAlign ||
        fallback.spineTitleAlign ||
        "left",
      color:
        source.spineTextColor ||
        sourceSpine.textColor ||
        fallback.spineTextColor ||
        "#ffffff",
      outlineColor:
        source.spineStrokeColor ||
        sourceSpine.strokeColor ||
        fallback.spineStrokeColor ||
        "#000000",
      outlineSize:
        Number(source.spineStrokeSize ?? sourceSpine.strokeSize) ||
        Number(fallback.spineStrokeSize) ||
        0,
      rotate:
        source.spineTitleRotate !== undefined
          ? source.spineTitleRotate !== false
          : sourceSpine.titleRotate !== false,
      customText: "",
    },
    {
      id: "spine-author",
      location: "spine",
      part: "author",
      enabled:
        source.spineAuthorOn !== undefined
          ? source.spineAuthorOn !== false
          : sourceSpine.authorOn !== false,
      size:
        Number(source.spineAuthorSize ?? sourceSpine.authorSize) ||
        Number(fallback.spineAuthorSize) ||
        4,
      x: 50,
      y: 94,
      width: 100,
      align: "center",
      color:
        source.spineTextColor ||
        sourceSpine.textColor ||
        fallback.spineTextColor ||
        "#ffffff",
      outlineColor:
        source.spineStrokeColor ||
        sourceSpine.strokeColor ||
        fallback.spineStrokeColor ||
        "#000000",
      outlineSize:
        Number(source.spineStrokeSize ?? sourceSpine.strokeSize) ||
        Number(fallback.spineStrokeSize) ||
        0,
      rotate:
        source.spineAuthorRotate !== undefined
          ? Boolean(source.spineAuthorRotate)
          : Boolean(sourceSpine.authorRotate),
      customText: "",
    },
  ];
};
TPP.migrateTextElements = function (book, base) {
  const defaults = TPP.defaultTextElements(book, base);
  const existing = Array.isArray(book.textElements) ? book.textElements : [];
  const byKey = new Map(
    existing.map(function (entry) {
      return [
        TPP.textElementKey(entry && entry.location, entry && entry.part),
        entry,
      ];
    }),
  );
  book.textElements = defaults.map(function (entry) {
    return Object.assign(
      {},
      entry,
      byKey.get(TPP.textElementKey(entry.location, entry.part)) || {},
    );
  });
  book.textElements.forEach(function (entry, index) {
    if (!entry.id) {
      entry.id =
        (defaults[index] && defaults[index].id) ||
        "text-" + TPP.textElementKey(entry.location, entry.part);
    }
  });
};
TPP.textElementContent = function (book, location, part) {
  const element = TPP.findTextElement(book, location, part);
  if (element && element.part === "custom") return element.customText || "";
  if (part === "title") return String((book && book.title) || "");
  if (part === "author")
    return location === "spine"
      ? String((book && (book.spineAuthor || book.author)) || "")
      : String((book && book.author) || "");
  if (part === "series")
    return [book && book.seriesName, book && book.number]
      .filter(Boolean)
      .join(" ");
  if (part === "publisher") return String((book && book.publisher) || "");
  if (part === "copyright") return String((book && book.copyright) || "");
  return element && element.customText ? String(element.customText) : "";
};
TPP.syncLegacyTextFieldsFromElements = function (book) {
  return book;
};
TPP.syncTextElementsFromLegacyFields = function (book) {
  const backCustom = TPP.findTextElement(book, "back", "custom");
  if (backCustom) {
    backCustom.customText = String(book.backText || "");
    backCustom.size = Number(book.backTextSize) || backCustom.size || 4.5;
    backCustom.y = Number(book.backTextY) || 0;
    backCustom.align = book.backTextAlign || backCustom.align || "center";
    backCustom.color = book.backTextColor || backCustom.color || "#ffffff";
  }
};
TPP.migrateCoverTextSettings = function (book, base) {
  const sharedColor = book.coverText || base.coverText;
  const sharedStroke =
    "coverStroke" in book ? book.coverStroke : base.coverStroke;
  const sharedStrokeColor = book.coverStrokeColor || base.coverStrokeColor;
  const sharedStrokeSize = Number.isFinite(Number(book.coverStrokeSize))
    ? Number(book.coverStrokeSize)
    : base.coverStrokeSize;
  if (!("coverShowTitle" in book)) book.coverShowTitle = true;
  if (!("coverTitleColor" in book)) book.coverTitleColor = sharedColor;
  if (!("coverAuthorColor" in book)) book.coverAuthorColor = sharedColor;
  if (!("coverSeriesColor" in book)) book.coverSeriesColor = sharedColor;
  if (!("coverPublisherColor" in book)) book.coverPublisherColor = sharedColor;
  if (!("coverAuthorSize" in book))
    book.coverAuthorSize = Number(book.coverMetaSize) || base.coverAuthorSize;
  if (!("coverSeriesSize" in book))
    book.coverSeriesSize = Number(book.coverMetaSize) || base.coverSeriesSize;
  if (!("coverPublisherSize" in book))
    book.coverPublisherSize =
      Number(book.coverMetaSize) || base.coverPublisherSize;
  if (!("coverTitleStroke" in book)) book.coverTitleStroke = sharedStroke;
  if (!("coverAuthorStroke" in book)) book.coverAuthorStroke = sharedStroke;
  if (!("coverSeriesStroke" in book)) book.coverSeriesStroke = sharedStroke;
  if (!("coverPublisherStroke" in book))
    book.coverPublisherStroke = sharedStroke;
  if (!("coverTitleStrokeColor" in book))
    book.coverTitleStrokeColor = sharedStrokeColor;
  if (!("coverAuthorStrokeColor" in book))
    book.coverAuthorStrokeColor = sharedStrokeColor;
  if (!("coverSeriesStrokeColor" in book))
    book.coverSeriesStrokeColor = sharedStrokeColor;
  if (!("coverPublisherStrokeColor" in book))
    book.coverPublisherStrokeColor = sharedStrokeColor;
  if (!("coverTitleStrokeSize" in book))
    book.coverTitleStrokeSize = sharedStrokeSize;
  if (!("coverAuthorStrokeSize" in book))
    book.coverAuthorStrokeSize = sharedStrokeSize;
  if (!("coverSeriesStrokeSize" in book))
    book.coverSeriesStrokeSize = sharedStrokeSize;
  if (!("coverPublisherStrokeSize" in book))
    book.coverPublisherStrokeSize = sharedStrokeSize;
  if (book.coverTitleStroke === false) book.coverTitleStrokeSize = 0;
  if (book.coverAuthorStroke === false) book.coverAuthorStrokeSize = 0;
  if (book.coverSeriesStroke === false) book.coverSeriesStrokeSize = 0;
  if (book.coverPublisherStroke === false) book.coverPublisherStrokeSize = 0;
  book.coverTitleStroke = true;
  book.coverAuthorStroke = true;
  book.coverSeriesStroke = true;
  book.coverPublisherStroke = true;
  if (book.spineStroke === false) book.spineStrokeSize = 0;
  book.spineStroke = true;
};
TPP.norm = function (book) {
  const base = TPP.fallbackBook();
  const out = Object.assign({}, base, book || {});
  out.signatureSize = TPP.signatureSize(out.signatureSize);
  out.sewingStations = TPP.sewingStations(out.sewingStations);
  out.sewingGuideOpacity = TPP.opacity(out.sewingGuideOpacity, 0.65);
  out.signatureGuideOpacity = TPP.opacity(out.signatureGuideOpacity, 0.65);
  out.mediaCaptionSize = TPP.mediaCaptionSize(
    out.mediaCaptionSize,
    base.mediaCaptionSize,
  );
  TPP.migrateCoverTextSettings(out, base);
  out.chapters =
    Array.isArray(out.chapters) && out.chapters.length
      ? out.chapters
      : base.chapters;
  out.chapters = out.chapters.map(function (chapter, index) {
    const normalized = Object.assign(
      {
        id: TPP.uid(),
        title: "Chapter " + (index + 1),
        text: "",
        imageId: "",
        imageElementId: "",
        imagePlacement: "none",
        imageZoom: 70,
        imageRotate: 0,
        level: 0,
        isSubsection: false,
        isMetadata: false,
        includeInToc: true,
        tocTitle: "",
      },
      chapter,
    );
    TPP.migrateChapterInlineImage(out, normalized);
    normalized.imageZoom = Math.min(
      100,
      Math.max(10, Number(normalized.imageZoom || normalized.imageWidth) || 70),
    );
    delete normalized.imageWidth;
    return normalized;
  });
  TPP.migrateTextElements(out, base);
  TPP.migrateImageElements(out, base);
  TPP.syncLegacyTextFieldsFromElements(out);
  TPP.syncLegacyImageFieldsFromElements(out);
  TPP.hydrateBookDates(out);
  TPP.normalizeFiles(out);
  TPP.syncCoverPreviewAsset(out);
  const fileIds = new Set(
    out.files.map(function (file) {
      return file.id;
    }),
  );
  ["coverImageId", "backImageId", "spineImageId"].forEach(function (key) {
    if (out[key] && !fileIds.has(out[key])) out[key] = "";
  });
  (Array.isArray(out.imageElements) ? out.imageElements : []).forEach(
    function (element) {
      if (element && element.fileId && !fileIds.has(element.fileId))
        element.fileId = "";
    },
  );
  out.chapters.forEach(function (chapter) {
    if (chapter.imageId && !fileIds.has(chapter.imageId)) chapter.imageId = "";
  });
  TPP.syncLegacyImageFieldsFromElements(out);
  TPP.syncCoverPreviewAsset(out);
  return out;
};
TPP.load = async function () {
  try {
    TPP.library = JSON.parse(localStorage.getItem(TPP.LIB) || "[]");
  } catch {
    TPP.library = [];
  }
  if (!TPP.library.length) {
    let sample = null;
    try {
      sample = await fetch("data/sample-book.json").then(function (response) {
        return response.json();
      });
    } catch {
      sample = TPP.fallbackBook();
    }
    TPP.library = [TPP.norm(sample)];
    TPP.save();
  }
  TPP.library = TPP.library.map(TPP.norm);
  TPP.bookFingerprints = {};
  TPP.bookDraftFingerprints = {};
  TPP.library.forEach(function (book) {
    const fingerprint = TPP.bookFingerprint(book);
    const bookId = TPP.bookId(book);
    TPP.bookFingerprints[bookId] = fingerprint;
    TPP.bookDraftFingerprints[bookId] = fingerprint;
  });
  const activeId = localStorage.getItem(TPP.ACTIVE);
  TPP.active =
    TPP.library.find(function (book) {
      return TPP.bookId(book) === activeId;
    }) || TPP.library[0];
};
TPP.loadStaleKeyLookup = async function () {
  if (
    typeof window !== "undefined" &&
    window.location &&
    window.location.protocol === "file:"
  ) {
    TPP.staleKeyLookup = TPP.clone(TPP.defaultStaleKeyLookup);
    return;
  }
  try {
    const response = await fetch("data/stale-key-lookup.json");
    if (!response.ok) throw new Error("lookup");
    const data = await response.json();
    TPP.staleKeyLookup =
      Array.isArray(data) && data.length
        ? data
        : TPP.clone(TPP.defaultStaleKeyLookup);
  } catch {
    TPP.staleKeyLookup = TPP.clone(TPP.defaultStaleKeyLookup);
  }
};
TPP.clearRevisionTimer = function (bookId) {
  if (!TPP.bookRevisionTimers[bookId]) return;
  clearTimeout(TPP.bookRevisionTimers[bookId]);
  delete TPP.bookRevisionTimers[bookId];
};
TPP.scheduleRevisionCommit = function (bookId, delay) {
  if (!bookId) return;
  TPP.clearRevisionTimer(bookId);
  TPP.bookRevisionTimers[bookId] = setTimeout(
    function () {
      const book = TPP.library.find(function (entry) {
        return TPP.bookId(entry) === bookId;
      });
      if (!book) return;
      TPP.save("commit", bookId);
    },
    Math.max(100, Number(delay) || 900),
  );
};
TPP.save = function (mode, bookId) {
  mode = mode || "commit";
  const targetIds = bookId
    ? [bookId]
    : TPP.library.map(function (book) {
        return TPP.bookId(book);
      });
  TPP.library.forEach(function (book) {
    const meta = TPP.bookMeta(book);
    const currentId = TPP.bookId(book);
    if (!targetIds.includes(currentId)) return;
    TPP.hydrateBookDates(book);
    const previous = TPP.bookFingerprints[currentId];
    const priorDraft = TPP.bookDraftFingerprints[currentId];
    const current = TPP.bookFingerprint(book);
    if (mode === "draft") {
      if (priorDraft !== current) {
        if (previous !== undefined && current !== previous) {
          meta.subrevision = TPP.bookSubrevision(book) + 1;
          meta.updatedAt = TPP.nowIso();
        } else {
          meta.subrevision = 0;
        }
      }
      TPP.bookDraftFingerprints[currentId] = current;
    } else {
      TPP.clearRevisionTimer(currentId);
      if (previous !== undefined && current !== previous) {
        meta.revision = TPP.bookRevision(book) + 1;
        meta.subrevision = 0;
        meta.updatedAt = TPP.nowIso();
      } else if (meta.subrevision) {
        meta.subrevision = 0;
      }
      TPP.bookFingerprints[currentId] = current;
      TPP.bookDraftFingerprints[currentId] = current;
    }
    TPP.compactBookMeta(book);
  });
  localStorage.setItem(TPP.LIB, JSON.stringify(TPP.library));
};
TPP.persistDerivedBookMeta = function (book) {
  if (!book) return;
  TPP.compactBookMeta(book);
  localStorage.setItem(TPP.LIB, JSON.stringify(TPP.library));
};
TPP.setActive = function (book) {
  TPP.active = book;
  localStorage.setItem(TPP.ACTIVE, TPP.bookId(book));
  TPP.loadForm();
  if (TPP.restoreReaderUi)
    TPP.restoreReaderUi(TPP.readSettingsUi ? TPP.readSettingsUi() : {});
  TPP.renderAll();
};
TPP.download = function (name, data) {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  TPP.downloadBlob(name, blob);
};
TPP.downloadBlob = function (name, blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = String(name).replace(/[/\\?%*:|"<>]/g, "-");
  link.click();
  URL.revokeObjectURL(url);
};
TPP.showProgress = function (pct, msg) {
  const wrap = document.getElementById("progress");
  const bar = document.getElementById("progressBar");
  const text = document.getElementById("progressText");
  if (!wrap || !bar || !text) return;
  wrap.hidden = false;
  bar.style.width = Math.max(2, Math.min(100, pct)) + "%";
  text.textContent = msg || "Rendering…";
  if (pct >= 100)
    setTimeout(function () {
      wrap.hidden = true;
    }, 800);
};
TPP.file = function (event, callback) {
  const file = event.target.files && event.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = function () {
    callback(reader.result, file);
  };
  reader.readAsDataURL(file);
};
